### ISSUE TITLE
column view support in IE

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/shinyFiles#1]
Add css support for the list view (columns of files)

**Comment by thomasp85** [comment]
There are general problems with column view in safari as well - there might be need for an alternative css.

**Comment by thomasp85** [comment]
Also in Chrome - wonder if the specifications have changed

**Comment by thomasp85** [comment]
Partially fixed in 00508da0. Now chrome has a weird selection bug in column view, where a different file than the one clicked, are being selected. Furthermore it still needs testing on IE

**Comment by vnijs** [comment]
IE 11 and Edge seem to work fine in my Windows 10 VM. There are also no problems that I can see in Chrome. I'll make the call here to close. If that is not what you want I'm sure you will let me know :)
