### ISSUE TITLE
Soflinks to folders are not working on dir chooser

### ISSUE THREAD

**Issue by raggaraluz** [thomasp85/shinyFiles#103]
After the upgrade to 0.7.1, the dir chooser is not poperly working with soflinks to directories.

They are displayed in the "Content" panel, but not in the "Directories" panel. Therefore, they cannot be selected or browsed.

In the image below, "data" is a softlink to a different folder (which is accessible from the user)

![imagen](https://user-images.githubusercontent.com/8734346/46728071-46c60f00-cc82-11e8-9f80-4240d95f3a0e.png)

**Comment by thomasp85** [comment]
My hunch is that this is related to the change to `fs` for file system access. @vinjs can you take a look when convenient

**Comment by raggaraluz** [comment]
Hi Thomas, you are true, it is related to `fs`.

I'm having a look at it myself and hopefully send a pull request during the day.

**Comment by vnijs** [comment]
Merged PR. Thanks @raggaraluz!

**Comment by raggaraluz** [comment]
Hi @vnijs, I've just checked in my machines and it works great with the workaround. Thanks a lot!
