### ISSUE TITLE
Directories not shown when using shinyDirChoose in macOS Mojave

### ISSUE THREAD

**Issue by AngelosPsy** [thomasp85/shinyFiles#106]
Hi,

Thank you for all your work; `shinyFiles` is an extremely useful package!

I recently bought a new laptop and I installed macOS Mojave. When I tried to run a shiny application, that used to work fine in Sierra, I encountered a problem when I use `getVolumes` inside the `shinyDirChoose` function. Specifically, the application returns the directory window, without however being able to select any directory; also the subdirectories included in the root directory (in the example below the root directory is Macintosh HD) are not shown. Here is a minimal example:

```{r}
library(shiny)
library(shinyFiles)

ui <- shinyUI(bootstrapPage(
  shinyDirButton('folder', 'Folder select', 'Please select a folder', FALSE)))

server <- shinyServer(function(input, output) {
  shinyDirChoose(input, 'folder', roots=getVolumes())
  return(print(getwd()))
})

runApp(list(ui=ui, server=server))
```

and here is the resulting window

![delete1](https://user-images.githubusercontent.com/5471828/47840766-add57000-ddb7-11e8-8273-8f14c3bde559.png)

I can, sort of, make this work by using the code below:

```{r}
library(shiny)
library(shinyFiles)

ui <- shinyUI(bootstrapPage(
  shinyDirButton('folder', 'Folder select', 'Please select a folder', FALSE)))

server <- shinyServer(function(input, output) {
  shinyDirChoose(input, 'folder', roots=c(wd = "."))
  return(print(getwd()))
})

runApp(list(ui=ui, server=server))
```
And the resulting window looks like this:
![delete22](https://user-images.githubusercontent.com/5471828/47840956-48ce4a00-ddb8-11e8-8be9-0c2347aa3a8d.png)

However, now I can see the directories/files in my working directory only and I cannot browse to the rest of the folders.

Do you know how I will be able to make `shinyDirChoose` point to the root directory?

```{r}
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyFiles_0.7.1 shiny_1.1.0     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19    crayon_1.3.4    digest_0.6.18   later_0.7.5     mime_0.6        R6_2.3.0        xtable_1.8-3    jsonlite_1.5    magrittr_1.5   
[10] pillar_1.3.0    rlang_0.2.2     rstudioapi_0.8  fs_1.2.6        promises_1.0.1  tools_3.5.1     httpuv_1.4.5    yaml_2.2.0      compiler_3.5.1 
[19] htmltools_0.3.6 tibble_1.4.2   
```

**Comment by vnijs** [comment]
Can you try the current version of shinyFiles in GitHub? Use the command below. I think that should already resolve the issue.

`remotes::install_github("thomasp85/shinyFiles")`

Also, does `shinyFiles::shinyFilesExample()` work on your system?

**Comment by AngelosPsy** [comment]
Thank you @vnijs! Updating to the most recent github version via `remotes` solved the problem. I will  close the use.

**Comment by vnijs** [comment]
Great! Thanks for reporting back @AngelosPsy 

@thomasp85 Unless you or @AFriendlyRobot have some ideas (and plans) to address https://github.com/thomasp85/shinyFiles/issues/101 could you push 0.7.2 on github to CRAN?

**Comment by xuefenfei712** [comment]
Thankyou for your answer, i also have this problem. i use your code and  the example command you posted here, though i can get the path and create a folder, whenever I click on the folder,  I got the warning message below, how to solver it, thankyou 

Warning in is.null(tree) || is.na(tree) :
  'length(x) = 7 > 1' in coercion to 'logical(1)'
Warning in is.null(tree) || is.na(tree) :
  'length(x) = 8 > 1' in coercion to 'logical(1)'
Warning in is.null(files$dir) || is.na(files$dir) :
  'length(x) = 3 > 1' in coercion to 'logical(1)'
