### ISSUE TITLE
directory problem with the update

### ISSUE THREAD

**Issue by kintany** [thomasp85/shinyFiles#109]
Hi, I'm using shinyFiles in my dockerized Shiny app and I've been very happy with how it was working, thank you for all your work.
But with the recent shinyFiles update it stopped working, here is the reproducible example: 
```
library(shiny)
library(shinyFiles)

ui <- fluidPage( # Application title
  mainPanel(
    shinyDirButton("dir", "Input directory", "Upload"),
    verbatimTextOutput("dir", placeholder = TRUE)  
  ))

server <- function(input, output) {
  shinyDirChoose(
    input,
    'dir',
    roots = c(home = '~'),
    filetypes = c('', 'txt', 'bigWig', "tsv", "csv", "bw")
  )
  
  global <- reactiveValues(datapath = getwd())
  
  dir <- reactive(input$dir)
  
  output$dir <- renderText({
    global$datapath
  })
  
  observeEvent(ignoreNULL = TRUE,
               eventExpr = {
                 input$dir
               },
               handlerExpr = {
                 home <- normalizePath("~")
                 global$datapath <-
                   file.path(home, paste(unlist(dir()$path[-1]), collapse = .Platform$file.sep))
               })
}

# Run the application
shinyApp(ui = ui, server = server)
```

When I run it, I get the following error:
```
Warning: Error in $: $ operator is invalid for atomic vectors
  75: unlist
  72: observeEventHandler [/Users/svetlana/test/app.R#32]
   1: runApp
```

So the problem is with dir()$path[-1]. Do I have to change it for the new version? Thank you!!

**Comment by vnijs** [comment]
All shinyFiles buttons now act as actionButtons do in shiny. They return a numeric values (e.g., 1, 2, 3, etc. depending on how many times they have been clicked). Once a directory (or file) has been selected the type will be a list with character data. So, you need to require the input is *not* numeric or *is* a list before proceeding. See your adapted code below. Hope that helps @kintany 

```
library(shiny)
library(shinyFiles)

ui <- fluidPage( # Application title
  mainPanel(
    shinyDirButton("dir", "Input directory", "Upload"),
    verbatimTextOutput("dir", placeholder = TRUE)  
  ))

server <- function(input, output) {
  shinyDirChoose(
    input,
    'dir',
    roots = c(home = '~'),
    filetypes = c('', 'txt', 'bigWig', "tsv", "csv", "bw")
  )
  
  global <- reactiveValues(datapath = getwd())
  
  dir <- reactive(input$dir)
  
  output$dir <- renderText({
    global$datapath
  })
  
  observeEvent(ignoreNULL = TRUE,
               eventExpr = {
                 input$dir
               },
               handlerExpr = {
                 req(is.list(input$dir))
                 home <- normalizePath("~")
                 global$datapath <-
                   file.path(home, paste(unlist(dir()$path[-1]), collapse = .Platform$file.sep))
               })
}

# Run the application
shinyApp(ui = ui, server = server)
```

**Comment by kintany** [comment]
Thank you, it works now but if I run it from Docker (sharing the directory with -v option) I now can't see my directory inside the shiny app. Used to work with the previous version though.

**Comment by vnijs** [comment]
It seems unlikely to me that this would be a shinyFiles issues as it works fine in a docker container that runs my radiant R-package as an Rstudio Addins. See link below to the container. That said, if you have a (simple) reproducible example I can look into it.

https://hub.docker.com/r/vnijs/radiant

![image](https://user-images.githubusercontent.com/2998956/48644822-aa85db00-e998-11e8-978c-f6d7d7023d6d.png)

**Comment by kintany** [comment]
Thank you!

This is my Dockerfile:

```
FROM r-base:latest

MAINTAINER Svetlana Vinogradova "kintany@gmail.com"

RUN apt-get update && apt-get install -y -t unstable \
    sudo \
    gdebi-core \
    make \
    gcc && \
    R -e "install.packages(c('shiny', 'shinyFiles'), repos='https://cran.rstudio.com/')" && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 3838

COPY shiny-server.sh /usr/bin/shiny-server.sh
COPY testDocker/ /srv/shiny-server/testDocker/

CMD ["/usr/bin/shiny-server.sh"]
RUN ["chmod", "+x", "/usr/bin/shiny-server.sh"]
```

This is the shiny-server.sh:
```
#!/bin/sh

Rscript -e ".libPaths('/usr/lib/R/library/'); shiny::runApp('/srv/shiny-server/testDocker/', launch.browser = F, port = 3838, host = '0.0.0.0')"
```

And I have a folder called "testDocker" with app.R there (code in the app is the same as in the example in the thread. 

I also pushed it here: https://github.com/kintany/docker_test

Thank you a lot @vnijs

**Comment by vnijs** [comment]
Try something like command below to run the docker container. You are running this app as root and, I assume, were not mapping `-v ~:/root`. 

```r
docker run --rm -p 3838:3838 -v ~:/root your-id/docker_test
```
