### ISSUE TITLE
How to set the progress bar in shinyFileChoose

### ISSUE THREAD

**Issue by 13479776** [thomasp85/shinyFiles#115]
How to set the progress bar in shinyFileChoose, when i upload the data?

**Comment by vnijs** [comment]
We currently don't have that functionality. Would welcome a PR though.

**Comment by 13479776** [comment]
but I want to show the status of uploaded data. Could you give some suggestion this through verbatimTextOutput()?  We can get the feedback about the information of uploaded data.
Thanks!

**Comment by vnijs** [comment]
I don't think this is easily possible. Shiny's fileInput first copies the full dataset to a temporary directory and then loads it. I believe this extra steps makes it possible for shiny to show a general data-loading progress bar. That is not how loading data works with shinyFiles, however. 

If you can figure out a good way to do this we can discuss adding it to shinyFiles. However, I'd recommend using something like `withProgress` wrapped around your data-loading code. It won't really tell the user how far along the loading process is but at least you can show and indicator that your app is working on something.

**Comment by 13479776** [comment]
Hi vnijs

I have got the code for the status of uploaded data. but there is always errors titled "$ operator is invalid for atomic vectors", when the app start.

Could you please give some help? Thanks@

the code
#############
library(shiny)
library(shinydashboard)

ui <- fluidPage(
  sidebarPanel(
    width=3,

  shinyFilesButton('files_XC', 'File select', 'Please select a file', FALSE),
  verbatimTextOutput("filechosen",placeholder = FALSE)
  
)
)
server <- function(input, output, session) {
  
  
  roots = getVolumes()
  
  ############ read xcmsfile
    
  shinyFileChoose(input, 'files_XC', roots=roots, filetypes=c('', 'csv'))
  
#check the data
  xc_set <- reactive({
    
    inFile1 <- parseFilePaths(roots, input$files_XC)$datapath
    
    
    dat_xc <- read.csv(inFile1)
    
    return(dat_xc)
  })
  
  
  
  file <- reactive(input$files_XC)

# return the status
  inf <- reactive({
    as.character(
      if(class(xc_set())== "data.frame") {
        infox <- paste(parseFilePaths(roots, input$files_XC)$datapath,"\n", class(xc_set()),"\n","Status: Load OK", sep = "")
        #print(infox)
      } else { "Status: error"}
    )
  })
  output$filechosen <- renderPrint({
    #inf()
    as.character(
      paste(parseFilePaths(getVolumes(),file()$datapath),inf(),sep = "")
    )
      })
  }


shinyApp(ui, server)
#######

**Comment by vnijs** [comment]
Closing for now. If you find a good solution I'd be open to reviewing a PR of course
