### ISSUE TITLE
Possibly isolate the initiation of the input$object to mimic shiny::fileInput() behaviour

### ISSUE THREAD

**Issue by nzxwang** [thomasp85/shinyFiles#116]
`shiny::fileInput()` sets the corresponding input variable to a dataframe upon file upload completion, which allows the user to user the corresponding input variable as the `eventExpr` to `shiny::observeEvent()` for observing a file upload.

As for `shinyFiles::shinyFilesButton()`, the corresponding input variable is updated every time the shinyFiles button is clicked or a file is uploaded. As such, to achieve the same function, one has to add a `shiny::req()` call to check if the corresponding input variable is empty.

Reprex:
```
runApp(list(
  
  ui = shinyUI(
    fluidPage(    
      shinyFilesButton('file', 'Load Dataset', 'Please select a dataset', FALSE),
      textOutput("txt")
    )
  ),
  
  server =shinyServer(function(input, output,session) {
    shinyFileChoose(input, 'file', roots=c(wd='.'))
    input_file <- reactive({
      parseFilePaths(roots=c(wd='.'), input$file)
    })
    rv <- reactiveValues()
    
    observeEvent(input_file(), {
      #if this req() line is commented, we get an error
      req(nrow(input_file())!=0 )
      rv$file <- input_file()$datapath %>% readLines()
    })
  })
))
```

Would you be open to a pull request that isolates the updating of the corresponding input variable until a file upload is completed to mimic `shiny:fileInput()` behaviour?

**Comment by vnijs** [comment]
I agree that it would be nice if shinyFiles was fully a "drop-in" alternative for `shiny::fileInput`. That would likely lead to breaking changes in shinyFiles, however, so I'm not really sure if it would be worth it. 

In shinyFiles, currently, information about a file is "transported" by appending information to an action button. Therefore the value *must* update on each click. 

I'd be happy to look at a PR but perhaps it would be best to start small to see if this is indeed a good and feasible path forward that would be worth a breaking change.

FYI Below an alternative to your reprex that only calls `input_file` when needed.

```
library(shiny)
library(shinyFiles)
runApp(list(

  ui = shinyUI(
    fluidPage(
      shinyFilesButton('file', 'Load Dataset', 'Please select a dataset', FALSE),
      textOutput("txt")
    )
  ),

  server =shinyServer(function(input, output,session) {
    shinyFileChoose(input, 'file', roots=c(wd='.'))
    input_file <- reactive({
      parseFilePaths(roots=c(wd='.'), input$file)
    })
    rv <- reactiveValues()

    observeEvent(input$file, {
      req(!is.integer(input$file))
      rv$file <- readLines(input_file()$datapath)
    })

    output$txt <- renderText({
      print(rv$file)
    })
  })
))
```

**Comment by vnijs** [comment]
Closing for now. As mentioned above, I'd be happy to look at a PR but perhaps it would be best to start small to see if this is indeed a good and feasible path forward that would be worth a breaking change.
