### ISSUE TITLE
Troubles selecting multiple files

### ISSUE THREAD

**Issue by alisimecn** [thomasp85/shinyFiles#120]
EDIT : fixed a typo that was in my example, but I still don't get the results I need

Hi,

I'm creating an app where I need to upload 2 different files, and I want it to be done with 2 separate shinyFilesButtons.

However, when I run my app, it works for the first file but not the second (I get a blank window for the second file). I think it has to do with multiple "shinyFileChoose" lines but I haven't seen anything addressing this issue. Is there any way to get around it ?

Thank you very much !

Here is a minimal example of code : 

```
library(shiny)
library(shinyFiles)


ui <- fluidPage(
  shinyFilesButton("file_1", "Select file 1", "File 1", multiple = F),
  shinyFilesButton("file_2", "Select file 2", "File 2", multiple = F),
  textOutput("txt_file1"),
  textOutput("txt_file2")
)


server <- function(input,output,session){
  
  volumes <- c(Home = fs::path_home(), "R Installation" = R.home(), getVolumes()())
  observe({
    shinyFileChoose(input, "file_1", roots = volumes, session = session)
  output$txt_file1 <- renderText(parseFilePaths(volumes, input$file_1)$datapath)
  })
  observe({
    shinyFileChoose(input, "file_2", roots = volumes, session = session)
  output$txt_file2 <- renderText(parseFilePaths(volumes, input$file_2)$datapath)
  })
    

}
shinyApp(ui = ui, server = server)

**Comment by alisimecn** [comment]
I fixed my example which didn't work because of a typo, but even though it works now, that's not exactly what I need to do. 

I would need to store the filepaths in reactive values, to be used afterwards (I need results obtained from file 1 when processing file 2), and I can't get any of the buttons to work with reactive : 

```
library(shiny)
library(shinyFiles)


ui <- fluidPage(
  shinyFilesButton("file_1", "Select file 1", "File 1", multiple = F),
  shinyFilesButton("file_2", "Select file 2", "File 2", multiple = F)
)


server <- function(input,output,session){
  
  volumes <- c(Home = fs::path_home(), "R Installation" = R.home(), getVolumes()())
  filepath_1 <- reactive({
    shinyFileChoose(input, "file_1", roots = volumes, session = session)
    return(parseFilePaths(volumes, input$file_1)$datapath)
  })
  filepath_2 <- reactive({
    shinyFileChoose(input, "file_2", roots = volumes, session = session)
    return(parseFilePaths(volumes, input$file_2)$datapath)
  })
}

shinyApp(ui = ui, server = server)

**Comment by 58675** [comment]
I have same issue. I can't upload 2 separate files from 2 buttons in an app with reactive function. Any help will be really appreciated.

**Comment by vnijs** [comment]
@alisimecn Buttons are already observers which you cannot put inside a reactive. Can you use the below?

```r
library(shiny)
library(shinyFiles)


ui <- fluidPage(
  shinyFilesButton("file_1", "Select file 1", "File 1", multiple = F),
  shinyFilesButton("file_2", "Select file 2", "File 2", multiple = F)
)


server <- function(input,output,session){
  
  volumes <- c(Home = fs::path_home(), "R Installation" = R.home(), getVolumes()())
  
  shinyFileChoose(input, "file_1", roots = volumes, session = session)
  filepath_1 <- reactive({
    return(parseFilePaths(volumes, input$file_1)$datapath)
  })
  
  shinyFileChoose(input, "file_2", roots = volumes, session = session)
  filepath_2 <- reactive({
    return(parseFilePaths(volumes, input$file_2)$datapath)
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by alisimecn** [comment]
Hi @vnijs thank you it does work. I was so sure that I had tried that in my more complex real code but maybe I hadn't. 
Anyways, I can't find the original code as I went a different route, but thanks for answering, hopefully it solves @58675's problem too.

**Comment by vnijs** [comment]
OK. Glad to hear that works. Will close this issue for now.

**Comment by 58675** [comment]
Thanks @vnijs  it works like a charm.
