### ISSUE TITLE
SSDM: Error in factors[[j]] : subscript out of bounds

### ISSUE THREAD

**Issue by priyamvadazsi** [thomasp85/shinyFiles#121]
I am trying to use the SSDM package in r. On using the following command line, I get an error. I get this error also when using the GUI. Pls help.

SDM <- modelling('GLM', subset(occ, occ$Species == 'monal'), Env, Xcol = 'Longitude', Ycol = 'Latitude', verbose = FALSE)

Error in factors[[j]] : subscript out of bounds
In addition: Warning messages:
1: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
  prediction from a rank-deficient fit may be misleading
2: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
  prediction from a rank-deficient fit may be misleading

**Comment by vnijs** [comment]
@priyamvadazsi Why would you think this has anything to do with shinyFiles?
