### ISSUE TITLE
Warning thrown by parseFilePaths()

### ISSUE THREAD

**Issue by elinw** [thomasp85/shinyFiles#123]
This line is throwing a warning, probably in the case where the object has more than one class.
https://github.com/thomasp85/shinyFiles/blob/master/R/filechoose.R#L506

**Comment by vnijs** [comment]
Thanks @elinw. There were actually several instances where this structure was used. I updated them to use `inherits` instead. See https://github.com/thomasp85/shinyFiles/commit/dd1b7acd61d085cae3813028390bd674ff8bf19e
