### ISSUE TITLE
Help Wanted: Cannot record shiny::fileinput directory with parseFilePaths

### ISSUE THREAD

**Issue by samuelfu2009** [thomasp85/shinyFiles#125]
Hi,

This package perfectly helped me record 'real' data path that shiny::fileinput can't:)

However, I found out that it doesn't work for the fileinput -> shinyFileChoose -> parseFilePaths. It always returns to an empty dataframe.

Here is a reproducible example which you can see that 'abc' returns to an empty dataframe.
`ui <- shinyUI(fluidPage(
  
  titlePanel("Example"),
  fileInput("abc", "bla")
  
))

server <- shinyServer(function(input, output, session) {
  
  observe({
    volumes = getVolumes()
    shinyFileChoose(input, "abc", roots=volumes, session=session)
    if(is.null(input$abc)){
      return(NULL)
    } 
    abc <<- parseFilePaths(volumes, input$abc)
  })
})

shinyApp(ui = ui, server = server)`

Much appreciated if you can please help me better understand why this is happening.

**Comment by vnijs** [comment]
Please take a look at the issue linked below. In shinyFiles you need to check for `is.integer` and not `is.null`.

https://github.com/thomasp85/shinyFiles/issues/116
