### ISSUE TITLE
shinyDirChoose when app deployed in shinyapp.io

### ISSUE THREAD

**Issue by c1au6i0** [thomasp85/shinyFiles#126]
I wrote down an [app](https://github.com/c1au6i0/rvent_app) that use the function  `shinyDirChoose` to select a folder and upload all its files, in a way similar to this [`post.`](https://stackoverflow.com/questions/48034976/shinyfiles-folder-selection-display-the-default-folder)
The function works perfectly when the app is running locally, but not when is deployed to shinyapp.io.
It appears to open up the volumes of the server where it's deployed instead of the client that is accessing the app.
This is the chunk where I use the function in the server
```
  shinyDirChoose(
    input,
    "dir",
    roots = c(home = '~'),
    filetypes = c("txt", "tsv", "csv")
  )
```
Under the same conditions, the function `shiny::fileInput` works file and  lets you browse the client computer. 
Am I missing something? 
Best

**Comment by vnijs** [comment]
shinyFiles: "A shiny extension for server side file access" When you use shinyFiles you will always see volumes on the machine the app is running on. If you want client access you will need shiny's fileInput
