### ISSUE TITLE
Trouble selecting file on Windows, but works on Mac/Linux

### ISSUE THREAD

**Issue by mikeyEcology** [thomasp85/shinyFiles#130]
Hi,
I'm working on an [R package that uses shinyFiles](https://github.com/mikeyEcology/MLWIC2) to select directories and files. Everything runs great on my Mac, but when I have a colleague test the Shiny App on a Windows machine she has one of two problems: 1) either she presses the select button and nothing occurs, or 2) no files show up in the window when she navigates to the directory. You can examine the [R functions that run this Shiny app here](https://github.com/mikeyEcology/MLWIC2/blob/master/R/classify_shiny2.R). 

Here is the code that will run the Shiny app
```
library(devtools)
devtools::install_github("mikeyEcology/MLWIC2")
library(MLWIC2)
MLWIC2::runShiny('classify')
```
I'd appreciate any help that you can provide.
Thank you

**Comment by vnijs** [comment]
@mikeyEcology I tried installing your app in Windows but ran into an error. Can you check if your colleague on Windows can run the example set in the shinyFiles package? I have a lot of students using shinyFiles on Windows and have not seen any issues at all. If your colleague does see errors when running the shinyFiles example, please provide as much detail as you can so we can figure out what might be going on.

**Comment by mikeyEcology** [comment]
Thank you for your response! We were able to get the problem sorted out by running the example.
