### ISSUE TITLE
Set "Details View" as default in shinySaveButton

### ISSUE THREAD

**Issue by carlosavellaneda8** [thomasp85/shinyFiles#132]
Hi,

I wanted to know if it is possible to set "Details View" as default using shinySaveButton. Currently, the default is "Icon View". 

Best regards, 
Carlos

**Comment by vnijs** [comment]
There is not a way to change the setting by default. However, I agree that the detail view might be the better default

**Comment by vnijs** [comment]
@carlosavellaneda8 I just pushed some changes to the version of shinyFiles on GitHub. If you run the example in inst/example you will see that `shinyFilesButton` and `shinySaveButton` in ui.R now use a new `viewtype` argument. The default `viewtype` is set to `detail` but you can still specify `list` or `icon` if you prefer. Please try it out using the code below

```r
if (!require("remotes")) install.packages("remotes")
remotes::install_github("thomasp85/shinyFiles")
```

**Comment by vnijs** [comment]
I'm closing this issue. Detail view will be the new default. Thanks for this suggestion @carlosavellaneda8. If you look at the example file in `inst/example`, you will see how you can change the default to `icon` or `list` view if you prefer. Also the example below.

```{r}
shinySaveButton(
    "save", "Save file", "Save file as...", 
    filetype = list(text = "txt", picture = c("jpeg", "jpg")), 
    viewtype = "icon"
)
```
