### ISSUE TITLE
passing shinyFileChoose object to normalizePath

### ISSUE THREAD

**Issue by mikeyEcology** [thomasp85/shinyFiles#133]
Hi,
I'm building an R package where users select an input csv so that I can run some functions on it. When I have them select paths using `shinyDirChoose`, I am able to pass this path to `normalizePath` without problem. But when I have them select a file with `shinyFileChoose`, I am unable to get `normalizePath` to recognize the output and I get the error: 
> Warning: Error in path.expand: invalid 'path' argument

I get this same error when I try `normalizePath` in a function outside of the shiny functions as well. 
I have tried following the [example here](https://github.com/thomasp85/shinyFiles/issues/116), but this does not solve my problem because it is trying to read in that file instead of just getting the path name. 

Here is an example where I'm having the user select a directory first (this works fine) and then select a file (this doesn't work). The function just prints the file path, but this is effectively all I need to do because I just need to capture the file path (normalized) as a variable in R. If I try running this without `normalizePath` for the filename, it works fine. 

```
# a function to print file names
print_file_name <- function(x,y){
  cat(paste0(x, "\n",
             y))
}

# server function
library(shiny)
library(shinyFiles)
server <- function(input, output, session) {
  
  volumes = shinyFiles::getVolumes()
  
  # input directory
  shinyFiles::shinyDirChoose(input, 'path', roots=volumes, session=session)
  dirname_path <- shiny::reactive({shinyFiles::parseDirPath(volumes, input$path)})
  # Observe path changes
  shiny::observe({
    if(!is.null(dirname_path)){
      print(dirname_path())
      output$path <- shiny::renderText(dirname_path())
    }
  })
  
  # input csv *** this is where the problem is. 
  shinyFiles::shinyFileChoose(input, "data_file", roots=volumes, session=session, filetypes=c('txt', 'csv'))
  # trying to treat filename the same as dirname - this leads to error 
  filename_data_file <- shiny::reactive({shinyFiles::parseFilePaths(volumes, input$data_file)})
  shiny::observe({
    if(!is.integer(filename_data_file)){
      print(filename_data_file())
      output$filename_data_file <- shiny::renderText(filename_data_file())
    }
  })
  # trying to treat filename differently
  #filename_data_file <- shiny::reactive({shinyFiles::parseFilePaths(volumes, input$data_file)[length(shinyFiles::parseFilePaths(volumes, input$data_file))]})
  
  # run print function
  shiny::observeEvent(input$runFun, {
    print_file_name(x=normalizePath(dirname_path()),
                    y=normalizePath(filename_data_file())
    )
  })
  
  #**** This works when I don't try to normalize path
  # filename_data_file <- shiny::reactive({shinyFiles::parseFilePaths(volumes, input$data_file)[length(shinyFiles::parseFilePaths(volumes, input$data_file))]})
  # shiny::observeEvent(input$runFun, {
  #   print_file_name(x=normalizePath(dirname_path()),
  #                   y=filename_data_file()
  #   )
  # })
  
  
}

# UI function
ui <- shiny::fluidPage(
  
  # App title ----
  shiny::titlePanel("print test"),
  
  # Sidebar layout 
  shiny::sidebarLayout(
    
    shiny::sidebarPanel(
      shinyFiles::shinyDirButton('path', 'directory', title='Select the directory'),
      shinyFiles::shinyFilesButton("data_file", "data file", title="select file", multiple=FALSE),
      #shiny::textInput("data_file", "data_file"),
      shiny::actionButton("runFun", "Run Function")
    ),
    mainPanel(
      shiny::helpText("main")
    )
  )
)

shiny::shinyApp(ui, server)
```

Thank you in advance for helping.

**Comment by mikeyEcology** [comment]
I'm still having the same problem, but I wrote a simpler example. The issue is that I want to take a file from `shinyFileChoose` and use this in a function in R. I can't figure out how to do this, but I have no problem passing `shinyDirChoose` to other functions in R.

```
library(shiny)
library(shinyFiles)
# example 
fun1 <- function(x){read.csv(x)}

# simple shiny code to read find a file and read it in. 
server <- function(input, output, session) {
  
  # base directory for fileChoose
  volumes = shinyFiles::getVolumes()
  # input_file
  shinyFiles::shinyFileChoose(input, "input_file", roots=volumes, session=session, filetypes=c('txt', 'csv'))
  #filename_input_file <- shiny::reactive({shinyFiles::parseFilePaths(volumes, input$input_file)[length(shinyFiles::parseFilePaths(volumes, input$input_file))]})
  filename_input_file <- shiny::reactive({shinyFiles::parseFilePaths(volumes, input$input_file)})
  
  # observe filename changes
  shiny::observe({
    if(!is.null(filename_input_file)){
      print(filename_input_file())
      output$input_file <- shiny::renderText(filename_input_file())
    }
  })
  
  # run the function
  shiny::observeEvent(input$runFUN, {
    fun1(normalizePath(filename_input_file()))
  })
}
ui <- shiny::fluidPage(
  
  # App title ----
  shiny::titlePanel("test"),
  
  # Sidebar layout with input and output definitions ----
  shiny::sidebarLayout(
    shiny::sidebarPanel(
      shinyFiles::shinyFilesButton('input_file', "file", title="Select a csv", multiple=FALSE),
      shiny::actionButton("runFUN", "run function")
    ), # this works with option 2
    
    
    # Main panel for displaying outputs ----
    shiny::mainPanel(
      
    )
  )
)

shiny::shinyApp(ui, server)
  
```

**Comment by vnijs** [comment]
shinyFiles uses an `actionButton` to pass along information about file paths. You need to use `is.integer` rather than `is.null`. See example linked below.

https://github.com/thomasp85/shinyFiles/blob/master/inst/example/server.R

**Comment by mikeyEcology** [comment]
Thank you for your help, but I still don’t see how I can use this to do something like reading a csv. After consulting this example, I modified my server function so that I have:

 shiny::observeEvent(input$runFUN, {
    if (is.integer(input$input_file)) {
      cat("No files have been selected (shinyFileChoose)")
    } else {
      fun1(parseFilePaths(volumes, input$input_file))
    }
  })

But this leads to the following error:
Warning: Error in read.table: 'file' must be a character string or connection

**Comment by vnijs** [comment]
@mikeyEcology Try the below. I recommend using simple "print" debugging liberally to see what values you are getting back from function calls. For example, if you print the return from the call to parseFilePaths you will see it is a data.frame (tibble). So your next step should be to extract the full path from that data.frame as you can see below.

  shiny::observeEvent(input$runFUN, {
    if (is.integer(input$input_file)) {
      cat("No files have been selected (shinyFileChoose)")
    } else {
      file_path <- parseFilePaths(volumes, input$input_file)
      data <- fun1(file_path$datapath)
      print(data)
    }
  })

**Comment by vnijs** [comment]
Closing for now as this seems resolved. Reopen if needed
