### ISSUE TITLE
shinyDirChoose does not work inside of a reactive

### ISSUE THREAD

**Issue by Matthewh19** [thomasp85/shinyFiles#138]
Hello! 
So I am working on a shiny app, and I am trying to use shinyFiles since it is such a great package. I am running into a problem though because I want people to be able to specify a projects root if they want (since this is to be run locally on people's computers), so I have a text box for users to paste their root into, but I also want it to be optional so that if someone wants to just click through their whole file structure they can. I have gotten it working fine with selecting files with shinyFileChoose inside a reactive, but for some reason I can't get it to work for selecting folders. Here is an example that I made (the actual app is very large):

```R

library(shiny)
library(shinyFiles)

ui <- fluidPage(

  titlePanel("Example App"),


  mainPanel(
    textInput("root", "Please enter your project folder root:"),
    h5(strong("Choose QSF Survey File:")),
    shinyFilesButton('file1', "Browse...", "Choose QSF Survey File", multiple = FALSE),
    verbatimTextOutput("qsf_path"),
    h5(strong("Sheets Folder Selector:")),
    shinyFiles::shinyDirButton(id = 'sheets_dir', label = "Folder select", title = "Sheets Folder Selector"),
    verbatimTextOutput("sheets_dir")
  )
)


server <- function(input, output, session) {

  Theroots <- reactive({
    if(input$root == ""){
      volumes <- getVolumes()()
      Theroots <- c(volumes)
    } else{
      Theroots <- c(project_root = input$root)
    }
    return(Theroots)
  })



  Theqsf_path <- reactive({
    shinyFileChoose(input, 'file1', roots = Theroots(), filetypes=c('qsf'), session = session)
    qsf_path <- parseFilePaths(roots = Theroots(), input$file1)
    return(qsf_path)
  })

  output$qsf_path <- renderPrint({
    Theqsf_path()
  })


  Thesheets_dir <- reactive({
    shinyDirChoose(input = input, 'sheets_dir',
                               roots = Theroots(), session = session)
    sheets_dir <- parseDirPath(roots = Theroots(), input$sheets_dir)
    print(sheets_dir)
    return(sheets_dir)
  })

  output$sheets_dir <- renderPrint({
    Thesheets_dir()
  })

}



shinyApp(ui, server)

```

Any ideas about why shinyDirChoose can't be in a reactive block? Thank you!

**Comment by vnijs** [comment]
I'm about to select directories in your app. In fact, I'd recommend to use a directory selector to set the project base rather than have a user type it in

![image](https://user-images.githubusercontent.com/2998956/81357082-9f8ca200-9087-11ea-90d8-15f36d96c7c4.png)

**Comment by Matthewh19** [comment]
@vnijs Sorry the problem occurs when I try and paste a root in and then select a folder with the folder selector. The reason I am having it be something you paste in is that if someone has their folder open and they want to copy and paste in where they are.

**Comment by vnijs** [comment]
The best way to go would be an extension of the PR below. I'm fine using, for example, `C:/Users/me` instead of "Home". 

https://github.com/thomasp85/shinyFiles/pull/129

**Comment by Matthewh19** [comment]
I am not sure how I would use that PR for this. The benefit of having a textbox to enter in your root is that I then can have it set that path as the root for all of the different selectors. I also just practically have it working, there is just something going wrong with the folder selector.

**Comment by vnijs** [comment]
I think you would be better off using the directory selector to choose the root dir. That said, the below should work as you want it now.

```
library(shiny)
library(shinyFiles)

ui <- fluidPage(
  titlePanel("Example App"),
  mainPanel(
    textInput("root", "Please enter your project folder root:"),
    shinyFiles::shinyDirButton(id = 'sheets_dir', label = "Folder select", title = "Sheets Folder Selector"),
    verbatimTextOutput("sheets_dir")
  )
)

server <- function(input, output, session) {
  Theroots <- reactive({
    root <- input$root
    req(root, dir.exists(root))
    
    if(length(root) == 0 || root == ""){
      volumes <- getVolumes()()
      c(volumes)
    } else{
      c(project_root = root)
    }
  })
  
  Thesheets_dir <- reactive({
    shinyDirChoose(input, 'sheets_dir', roots = Theroots(), session = session)
    parseDirPath(roots = Theroots(), input$sheets_dir)
  })
  
  output$sheets_dir <- renderPrint({
    Thesheets_dir()
  })
}

shinyApp(ui, server)
```

**Comment by vnijs** [comment]
Closing for now. Reopen if needed.

**Comment by Matthewh19** [comment]
The problem is that now that doesn't work if I paste nothing in as a root. It should theoretically use getVolumes()() to get the roots, but the selector is just blank. I am sorry for opening this back up. I really do appreciate all of the help!

**Comment by vnijs** [comment]
Can you take a look at the issue below. I provided a solution there that might translate to your setting. Let me know

https://github.com/thomasp85/shinyFiles/issues/124
