### ISSUE TITLE
Copying files from my computer to the shiny server-side

### ISSUE THREAD

**Issue by KinSimon96** [thomasp85/shinyFiles#139]
Hello,

I'm sorry in advance if this question looks quite common or relatively simple, but  I'm definitely not used to it.

To make it short, I would like to copy some files from my lap into the server root, so every user can have access and use them for genomic downstream analysis. Here is how it looks like when the app is deployed:
![Annotation 2020-05-14 161614](https://user-images.githubusercontent.com/57133275/82100574-3b628180-970a-11ea-917f-980618e954ad.png)

Assuming that 3 files are in this folder: `~/SC_RNA_Seq/200205_cr-mm-AVE4-3bis-Decontaminated`, is it possible to copy them into one of the above folders ? (picture)
Or even better, create a specific folder containing genomic files?

Thank you very much.
Simon

**Comment by vnijs** [comment]
Nice idea but not possible with shinyFiles. It runs on the same machine as where shiny (server) runs (e.g., the server). You could use a regular fileInput to upload data from your laptop and write some code to save it where you want on the server.  Then you could use shinyFiles to access files on the server.
