### ISSUE TITLE
Weird issue with updating other inputs

### ISSUE THREAD

**Issue by yindeng** [thomasp85/shinyFiles#14]
First of all, thanks for this very useful package!

I ran into a very weird issue, and I created a minimal example below to demonstrate one aspect of the issue (I'm still trying to find a small example that replicates the bigger issue I'm having in my shiny application, but I was hoping fixing this issue may at least shed light on the bigger issue).

Here's what's going on: if you click on the "file select" and selects a new file, it's supposed to update the textbox below with the file's name, but nothing happens. The button "Update File Name" works as expected. Any ideas or suggestions?

Thanks,
Yindeng

ui.r
```r
library(shiny)
library(shinyFiles)

shinyUI(
  fluidPage(
    actionButton('update', 'Update File Name'),
    shinyFilesButton('file', 'File select', 'Please select a file', FALSE),
    textInput('fileName', 'File Name')
  )
)
```

server.r
```r
library(shiny)
library(shinyFiles)

shinyServer(function(input, output, session) {
  dirRoots <- c('R Installation'=R.home())

  shinyFileChoose(input, 'file', roots=dirRoots, session=session, restrictions=system.file(package='base'))

  updateFileName <- function(){
    file <- (parseFilePaths(dirRoots, input$file))
    updateTextInput(session, 'fileName', value=file$name)
  }
  observeEvent(
    input$file, updateFileName()
  )
  observeEvent(
    input$update, updateFileName()
  )

}
)
```

**Comment by thomasp85** [comment]
Hi Yindeng

Thanks for bringing this to my attention. It seems that there is an inability for shinyFiles to work directly with updateTextInput(), that probably stems from shinyFiles unbinding and rebinding of input variables as the file chooser is removed. I’ll have a look at this in the coming days, but cannot currently say how long it will take. It will be fixed eventually, though.

best

Thomas

**Comment by yindeng** [comment]
Hi Thomas,

That would make sense. I look forward to your fix.

Regards,
Yindeng

**Comment by thomasp85** [comment]
My suspicion was correct - I have changed the call stack to make sure that changes are only communicated back to the server once everything have been rebounded. It will be part of the 0.6.0 update that will happen in the near future...
