### ISSUE TITLE
Options to disable creating/renaming directories

### ISSUE THREAD

**Issue by dipterix** [thomasp85/shinyFiles#143]
I want to use `shinyFiles` on a server as directory chooser. However, I don't want users to accidentally rename/create folders. Is there any option to disable these functions?

**Comment by vnijs** [comment]
If you don't want users to create new directories you should be able to do that by setting (linux) user  permissions on the server before users have access. This would require admin privileges on the server. shinyFiles will just work with the permissions you have set.

**Comment by dipterix** [comment]
It'll be nice if we could do that on the server. However, in many cases we don't have control on file permission or the file needs to be writable, just not writable by shinyFiles. Now that shinyFiles respect Linux file permission, maybe we could just override that permission when launching instance?

**Comment by vnijs** [comment]
Happy to look at a PR for this feature.

**Comment by dipterix** [comment]
PR submitted.
