### ISSUE TITLE
ShinyFileChoose does not work with Internet Explorer

### ISSUE THREAD

**Issue by SaideSa** [thomasp85/shinyFiles#145]
Great package! But unfortunately running the ShinyApp externally in Internet Explorer does not work. The `shinyFileChoose()` does not react after clicking the `shinyFilesButton()`. 

> Example:
```
library(shiny)
library(shinyFiles)

ui <- shinyUI(bootstrapPage(
  shinyFilesButton('files', 'File select', 'Please select a file', FALSE)
))
server <- shinyServer(function(input, output) {
  shinyFileChoose(input, 'files', roots=c(wd='.'), filetypes=c('', 'txt'),
                  defaultPath='', defaultRoot='wd')
})

runApp(list(
  ui=ui,
  server=server
))
```

**Comment by vnijs** [comment]
There is not much I can do about that unfortunately. The only good news is that IEs marketshare is below 2% now I believe. Try the new edge browser which is based on Chromium.
