### ISSUE TITLE
On Ubuntu 14.04 only "Folder select" works while "File select" and "Save file" do not work using shinyFiles/inst/example

### ISSUE THREAD

**Issue by SamoPP** [thomasp85/shinyFiles#15]
On Ubuntu 14.04 only "Folder select" works while "File select" and "Save file" do not work using shinyFiles/inst/example . All the controls in "File select" and "Save file" examples are empty, nothing to choose from,...

**Comment by thomasp85** [comment]
That seems strange. What browser are you using? Can I get a screenshot of the issue as 'all controls' is a bit ambiguous:-)

**Comment by thomasp85** [comment]
I cannot replicate any problems on Ubuntu with either Chrome or Firefox. I will need a more detailed description of the issue as well as your system setup in order to investigate further...

**Comment by SamoPP** [comment]
Hi. I pulled latest code from github a few minutes ago and rebuild the shinyFiles package. So, here are the screenshots:

![file select error](https://cloud.githubusercontent.com/assets/4817398/6873685/72debc2c-d488-11e4-8ea9-5fb77c42f87a.png)
![folder select ok](https://cloud.githubusercontent.com/assets/4817398/6873694/7d91d528-d488-11e4-8a46-6f9756139d12.png)
![save file error](https://cloud.githubusercontent.com/assets/4817398/6873701/8491a376-d488-11e4-9a19-606f715f1ec9.png)

**Comment by SamoPP** [comment]
Actually, doing some more testing, Folder select is also not working. If I try and click on Volumes item in the drop down box (see picture above) app freezes.

Also, when I try and click the "up arrow" in "File select" app crashes and this the error:
Warning: Unhandled error in observer: subscript out of bounds
observe({
    dir <- input[[paste0(id, "-modal")]]
    if (is.null(dir) || is.na(dir)) {
        dir <- list(dir = "")
    }
    else {
        dir <- list(dir = dir$path, root = dir$root)
    }
    dir$dir <- do.call(file.path, as.list(dir$dir))
    newDir <- do.call("fileGet", dir)
    if (!identical(currentDir, newDir)) {
        currentDir <<- newDir
        session$sendCustomMessage("shinyFiles", list(id = id, 
            dir = newDir))
    }
    invalidateLater(updateFreq, session)
})

**Comment by thomasp85** [comment]
This seems very strange and appears to be specific to your system. Have you tried to open the app in another browser? Can you report on whether the issue persist in both Chrome and Firefox?

**Comment by thomasp85** [comment]
Also, can you report the results of running getVolumes() in R

**Comment by SamoPP** [comment]
So, I started fresh r session from terminal, then run getVolumes() (which returns function in my case which is strange), then again ran the example and opened in Chrome with same result as in Firefox - not working:
user@userVB:~$ R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> getVolumes()
Error: could not find function "getVolumes"
> library(shinyFiles)
> getVolumes()
function () 
{
    osSystem <- Sys.info()["sysname"]
    if (osSystem == "Darwin") {
        volumes <- list.files("/Volumes/", full.names = T)
        names(volumes) <- basename(volumes)
    }
    else if (osSystem == "Linux") {
        volumes <- c(Computer = "/")
        media <- list.files("/media/", full.names = T)
        names(media) <- basename(media)
        volumes <- c(volumes, media)
    }
    else if (osSystem == "Windows") {
        volumes <- system("wmic logicaldisk get Caption", intern = T)
        volumes <- sub(" *\\r$", "", volumes)
        keep <- !tolower(volumes) %in% c("caption", "")
        volumes <- volumes[keep]
        volNames <- system("wmic logicaldisk get VolumeName", 
            intern = T)
        volNames <- sub(" *\\r$", "", volNames)
        volNames <- volNames[keep]
        volNames <- paste0(volNames, " (", volumes, ")")
        names(volumes) <- volNames
    }
    else {
        stop("unsupported OS")
    }
    if (!is.null(exclude)) {
        volumes <- volumes[!names(volumes) %in% exclude]
    }
    volumes
}
<bytecode: 0x25df558>
<environment: 0x25f5738>
> shinyFilesExample()
Loading required package: shiny

Listening on http://127.0.0.1:4532
Warning: Unhandled error in observer: subscript out of bounds
observe({
    dir <- input[[paste0(id, "-modal")]]
    if (is.null(dir) || is.na(dir)) {
        dir <- list(dir = "")
    }
    else {
        dir <- list(dir = dir$path, root = dir$root)
    }
    dir$dir <- do.call(file.path, as.list(dir$dir))
    newDir <- do.call("fileGet", dir)
    if (!identical(currentDir, newDir)) {
        currentDir <<- newDir
        session$sendCustomMessage("shinyFiles", list(id = id, 
            dir = newDir))
    }
    invalidateLater(updateFreq, session)
})

**Comment by thomasp85** [comment]
My bad for being imprecise. Can you run:

library(shinyFiles)
volumes <- getVolumes()
volumes()

and send me the results?

**Comment by SamoPP** [comment]
> volumes <- getVolumes()
> volumes()
                      Computer                            apt 
                           "/"                  "/media//apt" 
                           dvd                    userx 
                 "/media//dvd"          "/media//userx" 
                  sf_0000-0001           sf_backup_22.08.2011 
        "/media//sf_0000-0001" "/media//sf_backup_22.08.2011" 
            sf_userx_dev                         sf_tmp 
  "/media//sf_userx_dev"               "/media//sf_tmp" 

Note: I replaced my original user with userx... I am using VirtualBox Ubuntu guest on Ubuntu host...

**Comment by thomasp85** [comment]
It seems to be doing what it should be doing - Do you know how to access the developer tools in Chrome?

If so, can you see if there are any errors occuring when you summon a file chooser?

**Comment by SamoPP** [comment]
Here are the errors in Chrome when I press select file:
Uncaught TypeError: undefined is not a functionshinyFiles.js:596 populateFileChoosershinyFiles.js:563 createFileChoosershinyFiles.js:1710 (anonymous function)jquery.min.js:3 n.event.dispatchjquery.min.js:3 r.handle

**Comment by SamoPP** [comment]
Hi Thomas,

Any update on this issue? How can I help you debug this?

Best regards,
Samo.

**Comment by thomasp85** [comment]
Sorry for being slow on this. With the latest update of Shiny (0.12) they have introduced some bugs that breaks shinyFiles. If you haven't updated yet (or can downgrade somehow) you can help if you know your way around the Chrome debugger. If so can you pinpoint where the code expects a function but gets undefined...

**Comment by SamoPP** [comment]
Good news. After installing latest version of shiny from github this magically works now. Thanks.

There is just one thing I do not understand whether it is a bug or a feature: I can only select folders on the left pane from the tree but not from the right pane... It would be nice that if clicked on the folder on the right pane that would show as selection result...

**Comment by thomasp85** [comment]
That's good to hear. There have been some bugs in the latest version of Shiny that affected shinyFiles but I didn't expect them to cause what you described. Glad it solved itself out.

Regarding the functionality of the dirchooser, the right window is thought as a glimpse into the selected folder and not a navigation tool. The idea is that the user could be reassured that it was indeed the correct folder they had chosen. In that vein I would call it a 'feature' :-)
