### ISSUE TITLE
use shinyFiles with RSC?

### ISSUE THREAD

**Issue by MayaGans** [thomasp85/shinyFiles#150]
hello and thank you for the wonderful package! I was wondering if/how it'd be possible to use this package with rstudio connect or are files only accessible locally by design?

**Comment by vnijs** [comment]
shinyFiles provides access to files on the system running the shiny app. That means it will allow access to files on the server running Shiny Server. I have not (yet) used Rstudio Connect but I don't see why that would be any different. You should try running the example linked below on your server and figure out to set up the apps you want to use or develop

https://github.com/thomasp85/shinyFiles/tree/master/inst/example

**Comment by MayaGans** [comment]
Hi @vnijs thank you so much for your prompt reply. My mental model was wrong and I phrased my question incorrectly -- when deployed the folders on my local machine are available (woohoo) but my company uses another drive which it doesn't look like I have access to once the app is deployed. Is there a way to get network drives as options in the file explorer?

**Comment by vnijs** [comment]
Take a look at:

https://www.rdocumentation.org/packages/shinyFiles/versions/0.8.0/topics/getVolumes
