### ISSUE TITLE
Any way to share or pass "last position in file system" between shinyFiles buttons?

### ISSUE THREAD

**Issue by JoshOBrien** [thomasp85/shinyFiles#151]
The `?shinyFiles-buttons` help page notes that:

> The last position in the file system is automatically remembered between instances, but not shared between several shinyFiles buttons. 

I am developing an app that requires upload of several files that are likely to have been stored in the same directory on a user's computer. It would be very nice if users didn't have to repeatedly navigate to the same directory to upload the various files.

Is there currently any way to update the data structure underlying a **shinyFiles** button with a user-supplied "last point in the file system"? If not, is that because it would pose a security risk, or just because it hasn't been a priority?

I'm asking because if it is possible but just not implemented (and isn't in your opinion prohibitively complicated) I'd take a stab at adding the functionality.

**Comment by vnijs** [comment]
Why not just upload multiple files at once? I guess I'm missing why you would need more than "The last position in the file system is automatically remembered between instances"

**Comment by JoshOBrien** [comment]
The app I'm working on maps several spatial features onto a leaflet-based map. The spatial features are also used as inputs to a geospatial model, and attached each feature, the model requires a number of other user-supplied parameters. 

I've set things up so that each required spatial feature gets its own tab. On each tab is: (1) a file upload button;  (2) a `selectizeInput()`, dynamically updated based on the uploaded spatial file, that allows users to select an ID column from among its attribute columns; (3) and other parameters associated with that spatial feature. 

This makes for an intuitive user interface, but does require that a separate button be used for uploading each spatial file.

**Comment by vnijs** [comment]
Thanks for that @JoshOBrien. I think it would be a fair amount of work to add this to shinyFiles and it is not obvious to me that this would be something many others would need. It might be easier to use some action buttons on other pages and then figure out some JS that would send a click event to the main shinyFiles. I haven't tried this but I think it should be possible

**Comment by JoshOBrien** [comment]
@vnijs Would you mind explaining what you mean by "the main shinyFiles"? Would the approach you're envisioning work without setting up a *shinyFiles* button with `shinyFilesChoose()`? 

Or do you mean that my shiny UI would include one call to `shinyFilesChoose()` to set up a **shinyFile** button, as well as several action buttons (one per tab that needs to upload a file), each of which executes a click on that same **shinyFile** button?

Thanks for helping me think this through!

**Comment by vnijs** [comment]
The 2nd option. It has been quite some time since I did something like this in my radiant.data package (https://github.com/radiant-rstats/radiant.data). In the JS code below `#state_save` is a shinyFiles button and `#state_save_link` is a regular shiny action link. When a user clicks on the `#state_save_link` the `#state_save` modal is opened so this could be your action button on another tab. 

```
$(function(){
  $("#state_save_link").on('click', function(e){
    e.preventDefault();
    $("#state_save").trigger('click');
  });
  $("#state_load_link").on('click', function(e){
    e.preventDefault();
    $("#state_load").trigger('click');
  });
  $("#state_upload_link").on('click', function(e){
    e.preventDefault();
    $("#state_upload").trigger('click');
  });
});
```

**Comment by JoshOBrien** [comment]
@vnijs Thanks! That is super helpful. Between the code and your comments and the comments preceding it [in your radiant.data repo](https://github.com/radiant-rstats/radiant.data/blob/fe8e388a03b6e70d217051ed769fadc77d27caf0/inst/app/www/js/run_return.js), I should be able to figure this out. Will return here to post a minimal working example once I get it set up.

**Comment by JoshOBrien** [comment]
@vnijs Sure enough, that worked a charm. What a clever idea! A simple two-file reproducible example follows:


##### Contents of "www/myscript.js"
```js
$(function(){
  $("#dir2").on('click', function(e){
    e.preventDefault();
    $("#dir1").trigger('click');
  });
});
```

##### Contents of "app.R"
```r
library(shiny)
library(shinyFiles)

ui <- shinyUI(
  fluidPage(
    tags$script(src = "myscript.js"),
    shinyDirButton(id = "dir1",
                   label = "Select directory #1",
                   title = "Please select a directory"),
    div(),
    actionButton("dir2", "Select directory #2"),
  )
)

server <- function(input, output,session) {
    shinyDirChoose(input, "dir1",
                   session = session,
                   roots = c(wd = "~"))
}

shinyApp(ui = ui, server = server)
```

**Comment by vnijs** [comment]
Thanks for sharing the example @JoshOBrien. Very nice! I'll close this issue but feel free to post again if needed.
