### ISSUE TITLE
Folder navigation not limited

### ISSUE THREAD

**Issue by lz100** [thomasp85/shinyFiles#152]
I can change to parent folder(s) by typing "/.." on Linux, see image:
![Screenshot from 2020-10-23 20-34-31](https://user-images.githubusercontent.com/35240440/97067182-2527ee00-15e5-11eb-8f5b-57b8a44fd880.png)

**Comment by vnijs** [comment]
Thanks for reporting! @bellma-lilly could you take a look at this? I'd like to keep the option but this represent a security risk.

**Comment by bellma-lilly** [comment]
@vnijs @lz100 My proposed solution would be to normalize the requested path (which should resolve "..") and make sure the root is still included in the path. If not, we reset to the root. This allows the user to continue using ".." as long as it doesn't present a security risk:

    if(!startsWith(normalizePath(fulldir),normalizePath(currentRoots[root]))){
      #trying to go above the root
      fulldir <- path(currentRoots[root])
      dir = ""
    }

I'm not a security expert; please be critical so we get this fixed correctly. If this looks good, I will submit a PR.

**Comment by vnijs** [comment]
Thanks @bellma-lilly. My only concern here is what happens when an invalid path is provided and `normalizePath` throw an error. It would be good to try and "catch" that error if it occurs and have a default behavior that is secure.

**Comment by bellma-lilly** [comment]
@vnijs Thanks; I have integrated your suggestion into the PR #153

**Comment by vnijs** [comment]
@bellma-lilly It seems the PR breaks your previous work. For example, nothing happened whey I tried `Home/Desktop` or `Home/Dropbox`. I just realized this is because I am using WSL2 and `Desktop` is a symbolic link to the Windows Desktop. I then tried `fs::path_has_parent` which worked with symbolic links and avoided the `Home/..` problems that @lz100 mentioned. However, if I used `Home/Desktop/..` I ended up in the Windows user home directory. A bit of a surprise. So, I ended up with the below. @bellma-lilly Could you try this out and also add `path_norm path_has_parent` as imports from the `fs` package? If it works as intended for you as well, please update the PR and I will merge it.

```
    fulldir <- try(path_norm(fulldir), silent = TRUE)
    if (inherits(fulldir, "try-error") ||
        !path_has_parent(fulldir, currentRoots[root])) {
      fulldir <- path(currentRoots[root])
      dir <- ""
    }
```

**Comment by bellma-lilly** [comment]
@vnijs This works, and the code is cleaner.

**Comment by vnijs** [comment]
@lz100 Can you please check the master branch on github? Want to make sure there are no remaining security issues.

**Comment by lz100** [comment]
Hi @vnijs I tested and it fixed the issue from @bellma-lilly fork not from the master branch. I see you guys somehow closed that pull request rather than merging the pull request.

**Comment by vnijs** [comment]
My mistake. Merged now. Thanks for confirming @lz100!

**Comment by vnijs** [comment]
@bellma-lilly and @lz100 I ran into problems when `currentRoots[root]` was "/" and dir was "/home". See code example below. 

```
> library(fs)
> fulldir <- path("/", "/home")
> path_has_parent(fulldir, "/")
[1] FALSE
```

Fix commit linked below. Please try this out and let me know if you run into any edge cases.

https://github.com/thomasp85/shinyFiles/commit/ffa4e5f35968932d4eea30a197f23b42ec3aa4f7

**Comment by bellma-lilly** [comment]
@vnijs Does windows have a similar problem?

**Comment by vnijs** [comment]
I'm not seeing any issues on Windows. It is just linux (and I expect macOS) where this would come up.

**Comment by bellma-lilly** [comment]
@vnijs This change works for me. I might suggest removing the check for windows as it doesn't matter.

**Comment by vnijs** [comment]
I think I misunderstood your prior comment. It is important to have the check since "//" is used for networks drives on Windows.

**Comment by bellma-lilly** [comment]
got it; good point. I haven't used windows in a long time now, and I forget about that sort of thing

**Comment by vnijs** [comment]
I'll close this issue now. Thank you @lz100 for reporting this issue and thank you @bellma-lilly for the PR.
