### ISSUE TITLE
shinyDirButton has a layout problem on bs4Dash dashboard

### ISSUE THREAD

**Issue by jnhyeon** [thomasp85/shinyFiles#157]
shinyDirButton has a layout problem on bs4Dash dashboard (https://rinterface.github.io/bs4Dash/) 
It's been a long time ago.
Please make a fix.

Thank you.
![2021-03-31_160138](https://user-images.githubusercontent.com/3360511/113103575-68445800-923a-11eb-8dfb-bd135611391b.png)

**Comment by vnijs** [comment]
Closing. Pushing new version to CRAN soon
