### ISSUE TITLE
parseFilePaths is.na errors

### ISSUE THREAD

**Issue by lz100** [thomasp85/shinyFiles#159]
My  R has this stricter checks for `||` to check the length 1, so the following code in `parseFilePaths` no longer works

```r
if (is.null(selection) || is.na(selection) || is.integer(selection) ||  length(selection$files) == 0) 
```
I know if I use input$xxx from fileButton to pass to the selection, it is a list of more than one item so it will fail. To reproduce:

```r
Sys.setenv(`_R_CHECK_LENGTH_1_LOGIC2_`='true')
Sys.setenv(`_R_CHECK_LENGTH_1_CONDITION_`='true')
roots <- c(cur=getwd())
selection <- list(1,2)
shinyFiles::parseFilePaths(roots, selection)
```

**Comment by vnijs** [comment]
Thanks for reporting @lz100. Please try out the development version

```
remotes::install_github("thomasp85/shinyFiles", upgrade = "never")
```

**Comment by lz100** [comment]
Thanks, this fixed the issue.
