### ISSUE TITLE
Function "shinyDirButton" not found with R version 4.1.1

### ISSUE THREAD

**Issue by stephanmg** [thomasp85/shinyFiles#161]
Hello,

I'm faced with this warning message:

`Warning: Error in shinyDirButton: could not find function "shinyDirButton"`

Is this expected? Happy to share code snippets if required.

**Comment by vnijs** [comment]
Check that you have the latest version from CRAN (0.9.1). Then please double check that the example below works on your system.

```
shinyFiles::shinyFilesExample()
```

Also, please provide a reproducible example. Thanks

**Comment by stephanmg** [comment]
Hi @vnijs,

actually this happens only when deployed to `shinyapps.io` - your example works as well as my code - only deployed remotely won't work. Version is on the server 0.9.1.

**Comment by stephanmg** [comment]
Code is as follows: 

`ui.R`:
```
library("shinyFiles")

sidebar_content <- sidebarPanel(
   h2("Folder"),
   shinyDirButton("export_folder", "Select a folder", "Please select a folder", FALSE)
)

second_panel <- tabPanel(
  "Example",
  sidebarLayout(
    sidebar_content
  )
)

ui <- navbarPage(
  "Example",
  second_panel
)
```

`app.R`:

```
# Load data and libraries -------------------------------------------
library("shiny")
library("shinyWidgets")
library("shinyFiles")
source("ui.R")
source("server.R")

# Create shiny application 
shinyApp(ui = ui, server = server)
```
