### ISSUE TITLE
getVolumes - WMIC.exe deprecated

### ISSUE THREAD

**Issue by Mailinnia** [thomasp85/shinyFiles#163]
It seems that getVolumes on windows uses wmic.exe which is deprecated, so I can't use it to get all my drives.

_"The WMIC tool is deprecated in Windows 10, version 21H1 and the 21H1 semi-annual channel release of Windows Server. This tool is superseded by Windows PowerShell for WMI. Note: This deprecation only applies to the command-line management tool. WMI itself is not affected."_ [Windows 10 features we're no longer developing 12/01/2021](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features)

**Comment by vnijs** [comment]
I'm using the same version and it still seems to be working fine. Can you show what you are trying to do?

![image](https://user-images.githubusercontent.com/2998956/150624985-fd8b52ae-fa3f-48a4-8328-2dcaa3002497.png)

**Comment by Maillinia** [comment]
I'm using windows11 insider and wmic.exe does not exist there

**Comment by vnijs** [comment]
We can't make any changes until a clear replacement is available. Unfortunately it is not clear to me (yet) what that would be. It would have to be something that works on both Windows 10 and Windows 11

https://github.com/thomasp85/shinyFiles/blob/master/R/aaa.R#L82-L86

If you have suggestions, or want to create a pull request, please let us know

**Comment by Maillinia** [comment]
It can be replaced by running a powershell command:

```
volLetter <- system2('powershell', '(get-volume).driveletter', stdout=TRUE)
volumes <- paste0(volLetter, ':/')
names(volumes) <- paste0(volLetter, ':')
```

As I don't have wmic I don't know how the volume names usually look when using getVolumes()

All Windows come installed with [powershell ](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-5.1).

**Comment by vnijs** [comment]
Thanks for this starting point. However, on my system that only get the C drive. Not the 3-4 other mounted drives. I think Get-PSDrive may be the tool we will need. If you have ideas, please us know. 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-psdrive?view=powershell-7.2

**Comment by Deavd9** [comment]
I had the problem that `getVolumes()()`  didn't show the correct names (NANA and empty), didn't include USB-Drives and printed a warning on every call:

_Warning in system(paste(wmic, "/FAILFAST:1000 logicaldisk get VolumeName"),  :
  running command 'C:\WINDOWS\System32\Wbem\WMIC.exe /FAILFAST:1000 logicaldisk get VolumeName' had status 44003_

I came up with a solution that worked for me using PowerShell:
```
      volumes.name <- system2("powershell", "([System.IO.DriveInfo]::GetDrives()).Name", stdout = TRUE)
      volumes.label <- system2("powershell", "([System.IO.DriveInfo]::GetDrives()).VolumeLabel", stdout = TRUE)
      volumes <- system2("powershell", "([System.IO.DriveInfo]::GetDrives()).RootDirectory.Name", stdout = TRUE)
      
      volumes.name <- gsub(":\\\\$", ":/", volumes.name)
      sel <- volumes.label == ""
      volumes.label[sel] <- volumes.name[sel]
      volumes <- gsub(":\\\\$", ":/", volumes)
      names(volumes) <- volumes.label
```

I hope this can help

**Comment by vnijs** [comment]
Sorry for the delay. I adapted your code and included it in the GitHub version of shinyFiles. Please take a look and let us know if you encounter any issues. Thanks

BTW I recently upgrade to Win 11 and WMIC is still present. It is good to have this change, regardless

**Comment by vnijs** [comment]
@Mailinnia After a fair amount of testing the approach adapted from your code seems to work well. Thanks again for reporting!
