### ISSUE TITLE
Problem with window file names containing special characters

### ISSUE THREAD

**Issue by jllipatz** [thomasp85/shinyFiles#165]
With windows, using in a file entry name non standard characters such as those used in the french language make the file not choosable with shinyFiles. In the example, the last file is just a copy of the population.csv, which was given the name a.csv (but with an accent over the a). The display is wrong (probably because the characteristics of the file are not accessed) and th selected file name too.
The problem occured with the compiled CRAN version of the package using shinyFiles BUT NOT on the same code running from the source files on my computer. So perhaps there is a link with the future R 4.2 contents..
![vue shinyFiles](https://user-images.githubusercontent.com/24603698/158357730-b28b5290-00b5-458d-a634-8d8b3bfd57c3.png)
.

**Comment by jllipatz** [comment]
Sorry, the problem is not in shinyFiles nor in CRAN compilation but in the package "fs". Its version 1.5.2 doesn't read the file names correctly, but the previous I had (1.5.0)  didn't fail. I left the issue unclosed as I don't know what to do in such cases.

**Comment by vnijs** [comment]
Report to `fs`?

**Comment by jllipatz** [comment]
I did.

**Comment by vnijs** [comment]
Thanks. Can you link issue and/or report back what you learn?

**Comment by vnijs** [comment]
@jllipatz I'm going to close this issue for now. If there are things to do in `shinyFiles` please re-open or start a new issue. Thanks
