### ISSUE TITLE
Warnings for the lengths in conditions when choosing files and folders

### ISSUE THREAD

**Issue by pakom** [thomasp85/shinyFiles#167]
Hi and thank you for the wonderful package.

Today I updated to the latest R version (4.2.0). The [package I have](https://cran.r-project.org/package=RALSA) uses `shinyFiles` to choose input and output files and folders. Until the update to R 4.2.0 it all worked fantastic. After the update it still works, but warning messages started appearing in the console when I click on a `shinyFiles` button and choose files and folders in the dialog windows, such as:

`Warning in is.null(tree) || is.na(tree) :`
`  'length(x) = 8 > 1' in coercion to 'logical(1)'`

`Warning in is.null(files$dir) || is.na(files$dir) :`
`  'length(x) = 5 > 1' in coercion to 'logical(1)'`

`Warning in is.null(dir) || is.na(dir) :`
`  'length(x) = 2 > 1' in coercion to 'logical(1)'`

The actual numbers for the `length(x) = X` part differ for different `shinyFiles` buttons in the application, I assume it is also related with the lengths of the paths to files and folders. I managed to track the code quoted in the warnings to the following files in the `shinyFiles` package:

- `is.null(tree) || is.na(tree)` - [dirchoose.R](https://github.com/thomasp85/shinyFiles/blob/master/R/dirchoose.R), line 219
- `is.null(files$dir) || is.na(files$dir)` - [dirchoose.R](https://github.com/thomasp85/shinyFiles/blob/master/R/dirchoose.R), line 229
- `is.null(dir) || is.na(dir)` - [filesave.R](https://github.com/thomasp85/shinyFiles/blob/master/R/filesave.R), line 56

I am not sure what would be the reason for this, but I suppose it is related with one of the [latest changes in R (v4.2.0)](https://cran.r-project.org/doc/manuals/r-release/NEWS.html):
"Calling && or || with either argument of length greater than one now gives a warning (which it is intended will become an error)."

What really bothers me is the last part, "which it is intended will become an error".

Thank you in advance for your response.

**Comment by pakom** [comment]
I can now confirm the issue is found in Linux and Windows. [@jmcvw has confirmed in MacOS too](https://github.com/jmcvw/mrup/issues/4#issue-1224300322).

**Comment by vnijs** [comment]
Thanks for reporting @pakom! I pushed a fix to github. Please try out the development version and let us know if you notice any issues.

```
install.packages("remotes")
remotes::install_github("thomasp85/shinyFiles", upgrade = "never")
```

**Comment by jmcvw** [comment]
That fix seems to resolve all issues for me. Many thanks @vnijs.

**Comment by pakom** [comment]
@vnijs Thank you very much for the fixes!

However, now I experience a different issue with `shinyDirChoose`. When I click on the button to choose an input directory, no volume is listed in the drop-down menu on the top, although the tree on the left shows the content of the `C:` drive.
![Screen-2022-05-06_09-26-36](https://user-images.githubusercontent.com/15523823/167090278-32e335bb-407f-4b60-95d5-507b6ac9a0a7.png)



If I click on the drop-down list, it shows the volumes.


![Screen-2022-05-06_09-32-46](https://user-images.githubusercontent.com/15523823/167090304-7baf9404-3a7d-4290-ba87-a1ac68ff6b4a.png)


I can click on different volume, but the tree on the left is not updated, still shows the tree for the `C:` drive and the dialog says "Folder does not exist.


![Screen-2022-05-06_09-35-42](https://user-images.githubusercontent.com/15523823/167090335-41f1ad4c-acac-4295-aa25-3102bb1c6e42.png)


If I then click on any of the folders in the tree, the entire app crashes, dropping the following in the console:

`Warning: Error in if: argument is of length zero`
`  49: traverseDirs`
`  48: <Anonymous>`
`  46: sendDirectoryData`
`  45: observe`
`  44: <observer>`
`   1: shiny::runApp`

I had a look on the changes you did on lines 219 and 229. My initial thought before you implemented the changes that wrapping the conditions in `all()` would be the solution. What if `any()` approach is used instead?

For `fileChoose` and `fileSave` it all works fine, also confirmed by @jmcvw.

**Comment by jmcvw** [comment]
Hey @pakom. That's interesting. I have no issues with selecting volumes, or with the tree updating.

**Comment by jmcvw** [comment]
@pakom I also use `getVolumes()`. If I recall, the default is just supplied as the first volume "got". Would that work in your case?
For me, your issue only occurs on the "Convert data" and "Merge data" options. The others seem to default to 'Machintosh HD`, or 'Windows (C:)` where I can navigate the other folders as normal

**Comment by pakom** [comment]
@jmcvw Yes, you are right, you have `getVolumes()` in the `helpers.R` file, I missed it the first time.

Indeed, these issues occurs only in the "Convert data" and "Merge data" tabs in my app, but this is only because these are the only ones where `shinyDirChoose` is used. The reason why it works on your Mac which has one volume only that I can think of is that having one volume means having a vector of length 1 as output from `getVolumes`. This is exactly the issue with checking the conditions in `if (all(is.null(tree)) || all(is.na(tree))) {`, the latest change @vnijs made.

As for the solution you proposed, I am not sure. I am wondering about the performance issues I faced with your addin. After you made the changes I reinstalled the plugin and tried it, but the issue with the crash still persists and in Linux I never get to fully load the plugin(see [here](https://github.com/jmcvw/mrup/issues/5#issuecomment-1119754710)).

**Comment by vnijs** [comment]
@pakom I think I found the issue. Started in a previous comment. Please test the latest version on GitHub and report back if there are any issues. Thanks

**Comment by pakom** [comment]
@vnijs YES! Thank you very much for this. I tested all instances of `shinyFiles` buttons in my package and can confirm that there are no warnings, errors and crashes. Thank you once again!

@jmcvw Maybe you can check and confirm this too.

**Comment by jmcvw** [comment]
Excellent, everything works perfectly for me now too. Thanks @vnijs.

**Comment by pakom** [comment]
OK, happy to close this.

**Comment by vnijs** [comment]
Thanks @pakom and @jmcvw!

**Comment by gian-asco** [comment]
I would like to add that running the following example using the developmental version does not produce any warning or error both on ubuntu 18.04 and on macos

```
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "verbose")  #referee 1

library(shiny)
library(shinyFiles)

# Folder selections
ui <- shinyUI(bootstrapPage(  
    shinyDirButton('folder', 'Folder select', 'Please select a folder', FALSE)    
))

server <- shinyServer(function(input, output) {  
  shinyDirChoose(input, 'folder', roots=c(wd='.'), filetypes=c('', 'txt'))
})

runApp(list(ui=ui, server=server))
```
