### ISSUE TITLE
Using without modal

### ISSUE THREAD

**Issue by thecch** [thomasp85/shinyFiles#168]
I'm tying to use the content of the modal pop up directly within shiny it. However, I can't seem to find any function that offer this capability and was wondering if it is even possible. I don't want to start cannibalizing source codes without having the need to.

P.S. I can't find any official documentation on shinyFiles. Would greatly appreciate if someone can link it.

**Comment by vnijs** [comment]
You would have to setup your own JS code to extract information. Not straightforward. ShinyFiles documentation is here:

https://cran.r-project.org/web/packages/shinyFiles/shinyFiles.pdf
