### ISSUE TITLE
Feature request: allow a file chooser UI that doesn't pop up in a modal

### ISSUE THREAD

**Issue by daattali** [thomasp85/shinyFiles#176]
I have a use case where I'd like to add a file selector to a shiny app, but I want the file selection section to be embedded on the page rathern than appear in a modal after clicking a button. It would be great if that was supported by shinyFiles.

**Comment by thomasp85** [comment]
yeah, I remember thinking about that use case once I started building the package so I'm not opposed to it. I'm just not able to take on the development and don't know if @vnijs has the time for it.

That is to say, PRs are very welcome 🙂

**Comment by daattali** [comment]
I'm going to try looking for alternatives. If I REALLY need this I might come back and work on a PR

**Comment by daattali** [comment]
By the way, I ended up making one to suit exactly what I needed. It's mcuh less feature-rich than {shinyFiles}, much more simplistic. https://github.com/daattali/shinyfilebrowser (I don't see this one ever becoming as powerful as shinyFiles)

**Comment by nfuryn** [comment]
> By the way, I ended up making one to suit exactly what I needed. It's mcuh less feature-rich than {shinyFiles}, much more simplistic. https://github.com/daattali/shinyfilebrowser (I don't see this one ever becoming as powerful as shinyFiles)

Warning in install.packages :
  package ‘shinyfilebrowser’ is not available for this version of R :|

**Comment by daattali** [comment]
It's not on CRAN, only on github for now

**Comment by vnijs** [comment]
Closing for now.
