### ISSUE TITLE
Example in README.md returns error from root argument

### ISSUE THREAD

**Issue by machow** [thomasp85/shinyFiles#18]
When I try to run the example from the README, I get the following error..

`Unhandled error in observer: Roots must be a named vector or a function returning one`

I can run `shinyFilesExample()` without problem. Also, if I give a name to the root argument as in the example in `inst`..

`shinyFileChoose(input, 'files', root=c("R Inst" = R.home()), session=session, restrictions=system.file(package='base'))`

There isn't an error, but I can't see any files.

**Comment by machow** [comment]
This may be similar to Issue #15. I checked in chrome developer tools, and noticed I received this error when opening the file chooser..

`Uncaught TypeError: Cannot read property 'location' of undefined` (from shinyFiles.js:596)

I'm on Mac OSX, running Yosemite.

**Comment by thomasp85** [comment]
The first issue regarding the examples in readme is a blunder on my part and I will get it fixed. Sorry about that. 

When you say that the shinyFilesExample() works I expect you to mean that files are shown sand you're able to make selections? But when you build you're own app it doesn't work?

**Comment by machow** [comment]
Ah, I'm ashamed--I named the input 'file' in the ui but 'files' on the server. Sorry--the second part is completely my bad.

**Comment by machow** [comment]
One other question (I can open a new issue if it's useful), is it possible to load multiple files, similar to the multiple argument of `fileInput`? If you have any sense for how it might be implemented, I'm happy to take a pass at it.

**Comment by thomasp85** [comment]
If you mean selecting multiple files in the file chooser, then it is already implemented using `multiple=TRUE` in the call to `shinyFilesButton()`

**Comment by machow** [comment]
Fantastic! Thanks so much for your work on this--it looks really good!
