### ISSUE TITLE
Click the folder to expand

### ISSUE THREAD

**Issue by Yinlingzhu** [thomasp85/shinyFiles#180]
Click the folder to expand, can you modify it to click the folder text instead of just clicking on the left triangle. Current click triangle expansion folder for most users are not used to! 

鼠标点击文件夹展开，能否修改为点击文件夹文字而不是仅可以点击左侧三角。
当前点击三角展开文件夹对大多数用户来讲都不太习惯！

**Comment by vnijs** [comment]
Happy to review a PR.
