### ISSUE TITLE
Extra "/" when using parseSavePath

### ISSUE THREAD

**Issue by sjmgarnier** [thomasp85/shinyFiles#19]
When using parseSavePath, the returned datapath value has 2 extra "/" added to it just after the roots, making the path to the file incorrect. 

```{r}
parseSavePath(roots = c(Computer = "~/"), input$my_save)

       name      type                   datapath
1 test3.rmd rmarkdown ~///Desktop/test/test3.rmd
```

**Comment by thomasp85** [comment]
Wouldn't it work if you just removed the slash from the root declaration (making it ~ instead of ~/)

**Comment by sjmgarnier** [comment]
Will try when I get home. parseFilePaths doesn't have this problem.

**Comment by thomasp85** [comment]
Ok - I'll make sure they behave similarly
