### ISSUE TITLE
Multiple directories selection

### ISSUE THREAD

**Issue by vietmh** [thomasp85/shinyFiles#20]
Hi Thomas,

I'm using this package and like it very much. But did you support to select multiple directories ? If yes, please tell me how to do it.

Thanks.

**Comment by thomasp85** [comment]
It is not possible and not planned. Generally this is not possible in directory choosers from the major OSs so it is not an anticipated interaction for the user.

If you can come with a very compelling reason to implement it I'll consider it but my general feeling is that such a feature will lead to ambiguousness in the UI and confusion for the user...

**Comment by vietmh** [comment]
Hi Thomas, thanks for the quick answer. I write an open-source importer for a popular GC/MS platform (agilent) and they store each analysis in one directory. So It would be handy to choose multiple directories for processing. Or you maybe have another, better idea how to solve this problem?
Cheers
Viet

**Comment by thomasp85** [comment]
Yeah, agilent has some messed up output 'files' :-)

I would suggest that your users choses the directory containing the agilent 'files' instead. This will of course require them to select them all at once...

I'll think a bit about it

**Comment by thomasp85** [comment]
I know this is old and overdue. I've decided upon allowing directory selection in `shinyFileChoose` when the directory is file-like (that is, have an extension) and the extension is specifically mentioned in the `filetypes` argument. If this is still relevant for you I hope it will solve your issue.

It will be included in the next update
