### ISSUE TITLE
output update in shinyFileChoose

### ISSUE THREAD

**Issue by lorenzgerber** [thomasp85/shinyFiles#21]
Hi Thomas,

I'm playing around with your package, nice stuff!

I have a small issue: When I run shinyFileExample(), the fields 'verbatimTextOutput' containing the chosen files/dir never update. Same problem when I write a function by myself. Although, funny enough, on exiting with stopApp(), I get the chosen file/dir out. 

Cheers
Lorenz

**Comment by thomasp85** [comment]
Hi

You’re not the first today to mail me about that. This is due to a bug in shiny itself, which has been fixed but is not currently on CRAN

please install the version of shiny from github and everything should be fine.

best

Thomas

**Comment by lorenzgerber** [comment]
Thanks for the hint. Works perfect.
Cheers
Lorenz
