### ISSUE TITLE
Directory contains files but content shows "Empty folder"

### ISSUE THREAD

**Issue by qinzhu** [thomasp85/shinyFiles#24]
Hi Thomas,

It seems when using shinyDirButton to choose directory, in the modal interface, content part, only directories can be shown, and it shows "Empty folder" even if the folder contains files. I guess this is a bug?

Btw, your package is awesome.

Thanks,
Qin

![screen shot 2015-11-06 at 5 27 31 pm](https://cloud.githubusercontent.com/assets/10772232/11010270/b0a48b26-84ab-11e5-89fd-f8ed0271ac67.png)

**Comment by thomasp85** [comment]
Can you provide a reproducible example? Or is it specific to your system?

**Comment by qinzhu** [comment]
Example:
For ui.R:
```
require(shinyFiles)

shinyUI(bootstrapPage(
    shinyDirButton('data_folder', 'Select Data Folder', 'Please select a folder', FALSE)
))
```
For server.R,
```
shinyServer(function(input, output, session) {
    shinyDirChoose(input, 'data_folder', session=session, roots=c(home='~'), filetypes=c('', '.txt'))
})
```

I have a macbook with OSX EI Captitan, and the problem exists in chrome and the R-studio viewer. 

I guess this is system related?

**Comment by thomasp85** [comment]
I'll give it a look, but I'm a bit hung up next week, so can't promise a deadline

**Comment by qinzhu** [comment]
Cool. Thanks Thomas.

**Comment by jfhullo** [comment]
Any solution has been found ? I do have the same problem.

**Comment by thomasp85** [comment]
I've been quite away from all my personal projects for a while so sorry for the late reply...

The reason is likely that you pass a filetypes vector to shinyDirChoose - have you checked that your folders contain any txt files?

I'm on the same system and don't have any problems

**Comment by qinzhu** [comment]
I just ran the example again and the problem seems still there - and there are .txt files in that folder. Also I think the "Empty folder" is a litter counterintuitive even if the user specified a file type, because the folder is not empty. Maybe something like "Does not contain the specified file type" works better. I also find that, if I do not specify the filetypes argument, the folder contents are shown correctly. Not sure what went wrong with that. But I think it solves my problem.

**Comment by thomasp85** [comment]
try removing the dot from the filetype e.g. `.txt` -> `txt`

**Comment by SamGG** [comment]
I fall into the same error because of an old help or tuto, but I don't remember where it was. This repository seems to be OK.
HTH

**Comment by thomasp85** [comment]
There has been some lingering examples where extensions were erroneous specified with a dot - these have recently been fixed

**Comment by Basit403** [comment]
my file is showing empty file pls what is the solution amusing windows please
