### ISSUE TITLE
How can I add an icon to shinyFilesButton

### ISSUE THREAD

**Issue by omarbenites** [thomasp85/shinyFiles#26]
Hello Thomas,
I wonder If how I can add an icon to shinyFiles button. Here I have an example:

![image](https://cloud.githubusercontent.com/assets/5264796/12557423/a5f29dd0-c358-11e5-8488-33b1364b06ec.png)

Is it possible add a argument called 'icon' in shinyFiles( id,input, icon, ...)?

Thank so much in advance!

**Comment by thomasp85** [comment]
Sorry for the late answer. Thats a possible enhancement. I'll look into it when time permits (finishing a PhD atm). Until then, the html markup required for a shinyFiles button is quite simple and well documented so you could have a go at that...

**Comment by elcombato** [comment]
added in #50

**Comment by omarbenites** [comment]
Thanks!!
