### ISSUE TITLE
Can't run simple example in README

### ISSUE THREAD

**Issue by daattali** [thomasp85/shinyFiles#28]
I just tried running the very simple example in the README and I get an error.  Here's the complete app:

```
library(shiny)
library(shinyFiles)

ui <- fluidPage(
  shinyFilesButton('files', label='File select', title='Please select a file', multiple=FALSE)
)

server <- function(input, output, session) {
  shinyFileChoose(input, 'files', root=c(root='.'), filetypes=c('', '.txt'))
}

shinyApp(ui = ui, server = server)

```

The error:

```
Warning: Error in observerFunc: argument "session" is missing, with no default
Stack trace (innermost first):
    57: observerFunc
     4: <Anonymous>
     3: do.call
     2: print.shiny.appobj
     1: <Promise>
```

sessionInfo:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyFiles_0.6.0  shiny_0.13.1.9000

loaded via a namespace (and not attached):
 [1] R6_2.1.2          rsconnect_0.4.1.9 htmltools_0.3.5   tools_3.2.2      
 [5] Rcpp_0.12.3       RJSONIO_1.3-0     jsonlite_0.9.19   digest_0.6.9     
 [9] xtable_1.8-2      httpuv_1.3.3      mime_0.4 
```

I tried with and without declaring a `session` parameter in the server function

**Comment by thomasp85** [comment]
Does the example in the package work?

**Comment by daattali** [comment]
What's the example in the package?  I haven't looked too much into the
documentation, I just read the README.  Point me to a specific example?

---
http://deanattali.com

**Comment by thomasp85** [comment]
Run `shinyFilesExample()` and see if it gets you anywhere

**Comment by daattali** [comment]
Yes that works.

After looking into the source code a bit, I see the problem. `shinyFileChoose` expect a session parameter.  The example in the README does not provide a session argument. FYI you necessarily need the user to pass the session object, see [how I do it in shinyjs](https://github.com/daattali/shinyjs/blob/c03d054f48236456f75ccde3c494dfe79eab6c2c/R/utils.R#L7-L15)

**Comment by thomasp85** [comment]
I'm shamelessly stealing the `getSession` function then :-)

**Comment by daattali** [comment]
haha glad to help :)
