### ISSUE TITLE
Can't use shinyFiles without explicitly loading it via library()

### ISSUE THREAD

**Issue by daattali** [thomasp85/shinyFiles#29]
Here's a simple use of shinyFiles with namespacing instead of using library():

```
library(shiny)

ui <- fluidPage(
  shinyFiles::shinySaveButton("backup", "Save file", "Save file as...", filetype = list(RData = "RData"))
)

server <- function(input, output, session) {
  shinyFiles::shinyFileSave(input, "backup", roots = shinyFiles::getVolumes(),
                session = session, restrictions = system.file(package = "base"))
}

shinyApp(ui = ui, server = server)

```

This does not work.  When I look in the JS console, I see that there are errors trying to fetch JS and CSS files.  This pointed me to believe that the resources are not found because a resource path is not being declared.  It looks like the resource path [gets added when the package is attached](https://github.com/thomasp85/shinyFiles/blob/0ac21daa0837c1bb514d586ca1caeb7fb21d546d/R/aaa.R#L7-L9), which would explain why this happens.

It'd be nice to be able to use the package without having to call `library()`, because calling library() inside package code is bad and some people want to use your functions in other packages

**Comment by thomasp85** [comment]
I'll look into a fix but first after April as I have a PhD to hand in
