### ISSUE TITLE
OsX EI Capitan (10.11), unable to choose directory from user folder

### ISSUE THREAD

**Issue by qinzhu** [thomasp85/shinyFiles#31]
Recently I found the shinyDirChoose function stopped working when I set the root to c(wd = "~") in mac. The "Select" button does not respond to clicking. Also folders in home folder cannot be expanded to view the subdirectories. 

I read from the Latex updates that 'Under OS X 10.11, El Capitan, writing to /usr is no longer allowed, even with Administrator privileges'. I'm not sure if it's caused by the same issue or it's just my personal configuration issue.

Here's a minimal example.

server.R:
```
library(shiny)
library(shinyFiles)
shinyServer(function(input, output, session) {
    volumes <- getVolumes()
    shinyDirChoose(input, 'data_folder', roots=c(wd = '~'), session=session, restrictions=system.file(package='base'))
    output$directorypath <- renderPrint({parseDirPath(c(wd = '~'), input$data_folder)})
})
```
ui.R:
```
`
library(shiny)
library(shinyFiles)

shinyUI(bootstrapPage(
    shinyDirButton('data_folder', 'Select Data Folder', 'Please select a folder', FALSE),
    verbatimTextOutput('directorypath')
))
```

I would really appreciate if you could look into this. Thanks a lot!

**Comment by thomasp85** [comment]
Hi Qin

Sorry to hear that there is trouble. I'll look into it once I've handed in my PhD (a month from now)

**Comment by qinzhu** [comment]
Thanks a lot! Good luck with your PhD!

Qin

**Comment by thomasp85** [comment]
I cannot reproduce this problem on my own mac. Can you test again - possibly on another system..?

**Comment by qinzhu** [comment]
Hmm, the problem seems no longer there. Probably my configuration went wrong at that time. Thanks for checking it out.
