### ISSUE TITLE
shinyFilesExample File select doesn't work

### ISSUE THREAD

**Issue by HarlanH** [thomasp85/shinyFiles#35]
On this system:

> R version 3.2.1 (2015-06-18)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.9.5 (Mavericks)

with `shinyFiles_0.6.0` and `shiny_0.12.2`,

when I run `shinyFilesExample()`, the Folder Select button works fine, but the File Select button doesn't work at all. I get the attached mostly-blank window. None of the buttons do anything. There's no error in the console.

Any ideas?

<img width="927" alt="shinyfiles-issue" src="https://cloud.githubusercontent.com/assets/130809/16747166/cf62872c-478b-11e6-9f1c-d1f466bbe21c.png">

**Comment by thomasp85** [comment]
Please update shiny and report back on whether the problem persists...
