### ISSUE TITLE
Is it possible to initialize/reset the file/dir choosers?

### ISSUE THREAD

**Issue by burgerga** [thomasp85/shinyFiles#37]
For example, I would like to initialize the dir chooser to the working directory.
Or reset the form to the initial state.

**Comment by thomasp85** [comment]
That is not currently possible. I will consider adding this though

**Comment by cactus74** [comment]
I second that. An equivalent do update*Input() functions would be very useful.

Otherwise this a great and very useful package. Thanks a lot for this!

**Comment by thomasp85** [comment]
closed by 5cbf08f

**Comment by burgerga** [comment]
Nice work @thomasp85 and @zeehio, thanks!

**Comment by kikegoni** [comment]
Hey,

Thanks for implementing this package, find it super useful!!

I was wondering if it is possible to reset the value of a shinyFilesButton to their initial value once the files have been chosen. I am not able to, after selecting a file "A" and pressing a select button that resets all input to its initial state and I am unable to get the initial shinyFilesButton value. 

Is there any way to get this?

Thanks,

Kike

**Comment by vnijs** [comment]
We use shiny actionButtons under-the-hood and those cannot be reset
