### ISSUE TITLE
Companion tools: file explorer/manager, batch/queue

### ISSUE THREAD

**Issue by SamGG** [thomasp85/shinyFiles#39]
Hi,

It's a pleasure to use shinyFiles. 

In order, to integrate a set of tools via the shiny interface, did you plan to develop a file explorer or manager in order to:
- upload files asynchronously before processing them,
- review/browse HTML/markdown results if any.

In addition, a batch or a queue manager would be useful.

Best.

**Comment by SamGG** [comment]
For the file manager, I found a review
http://webeasystep.com/blog/view_article/Best_free_file_manager_alternatives_to_CKFinder
Most managers depend on PHP at server side, but one is offering clear specifications in order to implement the server side responses in any language
http://www.roxyfileman.com/api
Best.

**Comment by thomasp85** [comment]
shinyFiles currently has the feature level I set out to achieve when I wrote it. I've toyed with the idea of creating an embeddable (not a modal window) file browser as well, but currently I do not have time for this. It is unclear to me what the two bulletpoints entails. Uploading etc is all something that needs to be done outside of shinyFiles and so is any preview/display of files..?

**Comment by SamGG** [comment]
The batch/queue point aims to address a long computation after having setup its parameters with the help of Shiny.
The file manager point aims to address the need to upload and delete files. IMHO, these two features are sufficient features. Image display or thumbnail creation are unneeded features. Unfortunately I have not the skill to develop in Javascript/AJAX.
I do understand that these aims are not in the scope of your must have library.
Thanks for your answer.

**Comment by thomasp85** [comment]
shinyFiles reason d'etre is to allow different type of server-side file-system navigation. In the case of locally running apps the server and client filesystem happens to be the same. Upload of files to a server is best served by the standard approaches (`fileInput`). It's easy (though potentially dangerous) to offer deletion of files on the server using the shineFileChoose functionality in shinyFiles, and shinyDirChoose could potentially be used to choose the location for files uploaded with fileInput...

Does this make sense..?

**Comment by SamGG** [comment]
It makes sense.
My point concerns the upload process mainly. The objective of one of our Shiny app is to offer a down-sampling process of an uploaded file in order to ease the setting up of the computation of the whole data file.  The overall transfer/upload from the Web browser to a local Shiny server does not work correctly for a 150 MB file. This is the point I would like to address with a light file manager in R, without further installation of PHP or so.

**Comment by thomasp85** [comment]
Have you tried to change the file size limit? Anyway, if it is running locally you can simply choose the file with shinyFileChoose, right?

**Comment by SamGG** [comment]
File size limit is set to 2 GB during classical fileInput tests.
In-house (ie locally, intranet) the server access files using a share, and, shinyFiles allows the apps to run. That's perfect.
In order to offer the same processing to other users, and as a demo of the tools as well, we would like to allow those users to upload their own file (without any care of privacy). That why we need a file manager. Using R might sounds strange, but doing so might simplify software installation and would allow a standard look'n feel.
I do understand your points. Thanks for your questions that helped me in my objective. I am going to install one of these PHP managers in order to finalize the server shortly.

**Comment by thomasp85** [comment]
So you want users to browse files on there own compute and upload to a remote server? This will not be possible with either shinyFiles or any solution in other languages (PHP or others). The security is imposed at the browser level and no code running in the browser or server will be able to access the client file system...

**Comment by SamGG** [comment]
Sorry, my wording is may be incorrect. The idea is to propose to the user an upload manager (either the upload button or a drag'n drop zone) that is compatible with files of 150 MB (ie no timeout or whatever that cancels the upload). Then the user should be able to select those files, yet on the server, by use of shinyFiles. Such an uploader does not break the security on the client side. The file browser on the client side is the file selector offered by the client OS. Hope I correct my idea.

**Comment by thomasp85** [comment]
For the first part you have to rely on the mechanism provided by the browser, which is what `fileInput` wraps. Thus you have to find out why this does not work. It could be some settings unrelated to the server logic such as firewalls. PHP would use the same mechanics so it's hard to get around

**Comment by SamGG** [comment]
I didn't profile the problem yet. It occurred on two different servers under Linux, each installed differently. So I thought the failure depends on shiny service. But as Apache serves as a proxy for shiny apps, Apache could be faulty also. I will test independently Apache and Shiny.

**Comment by thomasp85** [comment]
Have you had any progress?

**Comment by SamGG** [comment]
I worked a little bit on it, but spent most of my time making applications work with shinyFiles. I came back to work this week. I will check. Thanks.
