### ISSUE TITLE
display two directories

### ISSUE THREAD

**Issue by joe-gz** [thomasp85/shinyFiles#42]
Hi, I see this issue was posted a while back (https://github.com/thomasp85/shinyFiles/issues/20). But i'm wondering if there is support to select one directory, display that tree, then go back and select a second directory and display them both. Do you have any advice for that?
Thank you!

**Comment by thomasp85** [comment]
Can you elaborate? I'm unsure what you want...

**Comment by joe-gz** [comment]
Hi, thanks so much for your reply! to elaborate further.. the below screen shot shows my current tree. I've selected one directory, and it's displayed as a tree exactly as i would want.  However, if i click on "Folder Select" again, and choose another directory, it replaces what is already there (which i totally understand is the correct purpose more often than not).  Do you have any advice to generate a second tree below what is already displayed there? Does that help clarify?

![screen shot 2016-08-29 at 11 00 14 am](https://cloud.githubusercontent.com/assets/10647670/18055952/e0773ac2-6dd7-11e6-8b53-21013afaeff1.png)

**Comment by thomasp85** [comment]
Isn't this a matter of how you handle the return value in server? Instead of overwriting the selected directory you should append to it?

If this is the case this has nothing to do with shinyFiles

**Comment by tgirgin23** [comment]
I believe what Joe is asking is if it is possible to upload a new folder to the already uploaded set of folders. So let's say the user uploads a folder containing multiple files, is there anyway the user can then add more files to the already uploaded set of files?

Thank you Thomas for your work on this package!
