### ISSUE TITLE
class "connection" warning

### ISSUE THREAD

**Issue by rfarouni** [thomasp85/shinyFiles#43]
Hi,

I am using Bioconductor pacakges in an Shiny app, and I keep getting this message 

`
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
`

If I am not mistaken, it seems to me that problem is caused by the RJSONIO package that ShinyFiles depends on. The class "connection" in RJSONIO is probably also the name of another class in BiocGenerics.

Is there a quick fix to this?

**Comment by zeehio** [comment]
@rfarouni Would you mind testing if the change from RJSONIO to jsonlite fixes your issue?

You can install the patched version with:
```r
devtools::install_github("zeehio/shinyFiles@possible_fix_43")
```

You can switch back to the latest shinyFiles CRAN version with

```r
install.packages("shinyFiles")
```

**Comment by tiagochst** [comment]
It solved for me. Thanks!

**Comment by zeehio** [comment]
Cool! Thanks for verifying! Now it is just a matter of merging the patches +1
