### ISSUE TITLE
shinyFilesSelect does not display anything when called from modalDialog

### ISSUE THREAD

**Issue by bbritten** [thomasp85/shinyFiles#44]
I'm trying to embed the `shinyFilesButton` into a modal provided by shiny version 0.14, and it doesn't seem to work quite as intended. MRE below.

```
# devtools::install_github("thomasp85/shinyFiles")
library(shiny) # version 0.14
library(shinyFiles)

ui = fluidPage(
  pageWithSidebar(
    headerPanel("Selections with Modals and shinyFiles", "shinyFiles w Modals"),
    sidebarPanel(
      helpText("The button below is used to display a modal with options to upload a file."),
      actionButton("upload", "Upload a File")
    ),
    mainPanel(
      verbatimTextOutput("filepath")
    )
  )
)

server = function(input, output, session) {
  shinyFileChoose(input, "file", roots=c("Root"=path.expand("~")), session=session)

  output$filepaths = renderPrint({
    parseFilePaths(path.expand("~"), input$file)
  })

  observeEvent(input$upload, {
    form = modalDialog(
      h4("Click the button below to choose your file"),
      shinyFilesButton("file", "Browse", "Please Select a File...", multiple=F), 
      title="Upload a File", 
      footer=modalButton("Submit"), 
      easyClose=F)

    showModal(form)
  })
}

shinyApp(ui, server)
```

Session Info:

```
Session info -------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.902)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-09-15                  

Packages -----------------------------------------------------------------
 package    * version date       source                               
 curl         1.2     2016-08-13 CRAN (R 3.3.1)                       
 devtools   * 1.12.0  2016-06-24 CRAN (R 3.3.1)                       
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)                       
 git2r        0.15.0  2016-05-11 CRAN (R 3.3.0)                       
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.1)                       
 httpuv       1.3.3   2015-08-04 CRAN (R 3.3.1)                       
 httr         1.2.1   2016-07-03 CRAN (R 3.3.1)                       
 jsonlite     1.0     2016-07-01 CRAN (R 3.3.1)                       
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.1)                       
 mime         0.5     2016-07-07 CRAN (R 3.3.1)                       
 R6           2.1.3   2016-08-19 CRAN (R 3.3.1)                       
 Rcpp         0.12.7  2016-09-05 CRAN (R 3.3.1)                       
 RJSONIO      1.3-0   2014-07-28 CRAN (R 3.3.0)                       
 shiny      * 0.14    2016-09-10 CRAN (R 3.3.1)                       
 shinyFiles * 0.6.2   2016-09-15 Github (thomasp85/shinyFiles@e354fe5)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)                       
 xtable       1.8-2   2016-02-05 CRAN (R 3.3.1)
```

**Comment by thomasp85** [comment]
I have little ressources for further work on shinyFiles so this is unlikely to see a fix from me. If you wish to submit a PR to fix this I would welcome it. I assume the problem lies in some of the javascript code not expecting multiple modals being possible.

**Comment by keqiang** [comment]
The `shinyFileChoose` function refreshes every 2 seconds and compares the current file list with the cached file list (`currentDir`). However the first time it runs when it's called from a modal dialog, the result will be sent to the client through `session$sendCustomMessage('shinyFiles', list(id=clientId, dir=newDir))` and at this time the UI button whose id is `clientId` is not yet initialized thus this message will fail to be processed by the client. This way, the client will initialize with an empty file chooser and the user can't change directory, this further results an empty input `dir <- input[[paste0(id, '-modal')]]` on which the `shinyFileChoose` function depends. It keeps refreshing the same directory and finds the cached result and the new result are identical so it won't send any new message to the client.

Tried a fix which will keep sending the message to client if the input `dir` is empty, it works most of the time but does fail sometimes as well.

**Comment by keqiang** [comment]
So, even the file list is successfully sent to the client side, it will also fail after the modal dialog closes and reopens.  This happens because `shinyFiles` assumes the UI that uses its functionality will remain existed in the DOM but this is not true in the case of a modal dialog because it will dismiss, thus after the modal dialog reopens, the `shinyFileChooseButton` will be re-created and as a result, it loses cached data `cacheData` which stores previous information. However, the button's id remains the same, so the server treats it the same and won't send it the file list because server still keeps a cached result that is identical to the new result(because the new result won't update until the client requests).

Maybe the client should cache the data in local storage, or notify the server to resend the information if a button doesn't have cached data.

**Comment by vnijs** [comment]
@keqiang Could you provide some more information on how you "Tried a fix which will keep sending the message to client if the input dir is empty ...."? Thanks. I'd very much like to know how to resend the information to be shown in the modal. Is caching even necessary? Could we not just get updated information when opening a new modal or creating a new directory?

See https://github.com/thomasp85/shinyFiles/pull/73 for a PR and discussion on getting shinyFiles to work with renderUI which has issues similar to the ones you discuss here. Any input / suggestions welcome.

**Comment by keqiang** [comment]
@vnijs The way I tried was to use localStorage and you can check the PR #68.  I will check #73 when I get time.
