### ISSUE TITLE
parseSavePath crashes if shinySaveButton does not have filetype

### ISSUE THREAD

**Issue by zeehio** [thomasp85/shinyFiles#45]
Hi,

Thanks for your work on this package and congratulations on your PhD (I assume you have finished it since there is a new version of shinyFiles around).

Going to the issue...:

If shinySaveButton does not have filetype specified, it is set to null by formatFiletype. Then parseSavePath will crash at the `data.frame(name = selection$name, type = selection$type, datapath = savefile)` because the `type` column will be NULL..

I am not familiar enough with shiny to provide a solution (maybe replacing the type if it is NULL by something else?). I hope the issue is clear enough and hopefully you will be able to fix this.

Thanks again!

**Comment by zeehio** [comment]
Also it may make sense to use  `stringsAsFactors = FALSE` in the data frame that is returned from parseSavePath.

**Comment by PeterVermont** [comment]
A workaround is to pass an empty list as the filetype:

`shinySaveButton('save', 'Save file', 'Save file as...', list('hidden_mime_type'=c())),`
