### ISSUE TITLE
Allow ability to use shiny bookmarking with shinyFiles

### ISSUE THREAD

**Issue by cmdcolin** [thomasp85/shinyFiles#54]
I thought it would be nice to have "bookmarkable app state" with shiny files enabled. I tried just switching on enableBookmarking but it seems maybe some extra work needs to be done to create "restore aware inputs" https://github.com/rstudio/shiny/wiki/Bookmarkable-state

**Comment by thomasp85** [comment]
This is indeed a good idea, unfortunately shinyFiles is currently on maintenance mode due to higher prioritised projects so I will not have time to implement this myself. I will however welcome a pull request and help with questions.

**Comment by cmdcolin** [comment]
Super! I was trying to look at it yesterday but not sure I got all the way

For example with this patch

```
diff --git a/R/filechoose.R b/R/filechoose.R
index 6a48b26..c216a11 100644
--- a/R/filechoose.R
+++ b/R/filechoose.R
@@ -329,6 +329,9 @@ shinyFileChoose <- function(input, id, updateFreq=2000, session = getSession(),
 #' @export
 #' 
 shinyFilesButton <- function(id, label, title, multiple, buttonType='default', class=NULL) {
+    value = restoreInput(id = id, default = '')
+    print("restoreInput")
+    print(value)
     tagList(
         singleton(tags$head(
                 tags$script(src='sF/shinyFiles.js'),
@@ -348,7 +351,7 @@ shinyFilesButton <- function(id, label, title, multiple, buttonType='default', c
             type='button',
             class=paste(c('shinyFiles btn', paste0('btn-', buttonType), class), collapse=' '),
             'data-title'=title,
+            'data-val'= value,

```

The restoreInput can get some of the info from a bookmark

```
[1] "restoreInput"
$files
$files$`0`
[1] ""         "Makefile"


$root
[1] "home"
```

But I was trying to figure out how to pass that info in, as just setting `data-val` didn't work. Maybe I need to look at the javascript?

**Comment by thomasp85** [comment]
There will definitely be need for modifying the javascript as the data-* properties needs to be updated every time something change

**Comment by vnijs** [comment]
@cmdcolin Could you explain exactly what you would want to bookmark? I think it might be easier to assign the return value from a `shinyFiles` selection to a reactiveValues object and bookmark that.

**Comment by cmdcolin** [comment]
I just had code where the user would select a file (on the server, using this module) and then it was very convenient to just be able to refresh the page and have it stay selected. Indeed, it might be possible to capture this with a reactive value. I just had the app hinged on the actual input value of this plugin.

Maybe close this issue for now :)
