### ISSUE TITLE
shinyFiles and shiny js bad interaction

### ISSUE THREAD

**Issue by PeterVermont** [thomasp85/shinyFiles#55]
There is bug if there are at least two shinyFile objects and at least one is created disabled with shinyjs, then the remaining enabled shinyFile object will show the file dialog TWICE. (or it could be that it opens the window twice and that I only see the underlying one when I close the top one).

Creating the item normally and later disabling it does not cause the bug -- it must be created disabled. They do not need to be the same kind of shinyFiles object.

I do not know if the bug is in shinyjs, shinyFiles or the interaction so I cross-listing it in both projects. Here is the link to the issue at shinyjs: https://github.com/daattali/shinyjs/issues/120

[shinyFiles_shinyjs_bad_interaction.zip](https://github.com/thomasp85/shinyFiles/files/907778/shinyFiles_shinyjs_bad_interaction.zip)

**Comment by daattali** [comment]
fixed on shinyjs 0.9.0.9001 (problem happened because shinyFilesButton returns a tagList that includes a head tag and shinyjs tripped up on that head tag because no other input I encountered before had that)

**Comment by PeterVermont** [comment]
Already fixed at shinyjs!
