### ISSUE TITLE
How do I use the shinyFilesButton and shinyFileChoose functions in flexdashboard

### ISSUE THREAD

**Issue by tarunparmar** [thomasp85/shinyFiles#69]
Any idea how do I use the shinyFilesButton and shinyFileChoose functions in flexdashboard...

I used it as it is with Shiny UI and Server functions but then its a bit limited to pass variables out of it. 

Will be nice to know if anyone tried this already.

**Comment by mrstlee** [comment]
I've had a similar same problem. I did a bit of scouting around with shiny.trace & found some differences between running shinyFiles as a UI+server, and using a simply shiny module (Code is attached in zip).

Initial SEND/RECV sequence using shiny module (Entries truncated):
    SEND {"recalculating":{"name":"__reactivedoc__","status":"recalculated"}}
    SEND {"custom":{"shinyFiles":{"id":"files","dir":{"files":{"filename":["c
    SEND {"busy":"idle"}                                                     
    SEND {"errors":[],"values":{"__reactivedoc__":{"html":"<!DOCTYPE html>\n<
    RECV {"method":"update","data":{".clientdata_output_sFflexd-chosen_hidden":false}}
    SEND {"busy":"busy"}                                                              
    SEND {"recalculating":{"name":"sFflexd-chosen","status":"recalculating"}}         
    SEND {"recalculating":{"name":"sFflexd-chosen","status":"recalculated"}}          
    SEND {"busy":"idle"}                                                              
    SEND {"errors":[],"values":{"sFflexd-chosen":"NULL"},"inputMessages":[]}          
    SEND {"busy":"busy"}                                                              
    SEND {"busy":"idle"}                                                              
    SEND {"busy":"busy"}                                                              

Initial SEND/RECV sequence running as UI+server (Entries truncated):

    SEND {"recalculating":{"name":"__reactivedoc__","status":"recalculated"}}
    SEND {"busy":"idle"}
    SEND {"errors":[],"values":{"__reactivedoc__ ... Lots of stuff
    SEND {"config":{"workerId":"","sessionId":"b8f623633749a601d5377339
    RECV {"method":"init","data":{".clientdata_output_filepaths_hidden"
    SEND {"busy":"busy"}                                               
    SEND {"custom":{"shinyFiles":{"id":"file","dir":{"files":{"filename
    SEND {"custom":{"shinyDirectories":{"id":"directory","dir":{"tree":
    SEND {"custom":{"shinySave":{"id":"save","dir":{"files":{"filename"
    SEND {"recalculating":{"name":"filepaths","status":"recalculating"}
    SEND {"recalculating":{"name":"filepaths","status":"recalculated"}}

A noticeable difference is that when running as UI+server the config and init messages are sent.
Note also that the custom 'shinyFiles' message containing the initial dir contents is sent after init & config in the UI+server case, but straightaway in the module case.


So it appears that an initialisation sequence is needed which doesn't happen in the module case. I guess it is something to do with using callModule to invoke the server from flexdashboard?

Could a delay help before invoking  callModule? I tried putting Sys.sleep in the flexdashboard code - no effect.

[sFflexdash.zip](https://github.com/thomasp85/shinyFiles/files/2108166/sFflexdash.zip)

**Comment by vnijs** [comment]
Simplified version of @mrstlee's example added below. It looks like the file path information is sent fine. However, the modal doesn't open. Just to check that flexdashboard does work with modals ... see Exhibit B

    ---
    title: "shinyFiles + flexdashboard"
    runtime: shiny
    output: flexdashboard::flex_dashboard
    ---
    
    ```{r setup, include=FALSE}
    library(shinyFiles)
    options(shiny.trace=TRUE)
    ```
    
    ### Exhibit A
    
    ```{r}
    shinySaveButton(
      "saveFileFlex", "Save file (renderUI)", "Save file as ...", 
    )
    shinyFileChoose(input, "saveFileFlex", roots = c(home = '~'), filetypes = c('', 'txt'))
    ```
    
    ### Exhibit B
    
    ```{r}
    actionButton("show", "Show modal dialog")
    observeEvent(input$show, {
      showModal(modalDialog(
        title = "Important message",
        "This is an important message!"
      ))
    })
    ```

**Comment by aravind211** [comment]
hey guys, any update on this issue. I am still unable to use shinyFiles with Flexdashboard?

**Comment by vnijs** [comment]
Looks like there is a more general issue trying to use Rmarkdown with runtime shiny together with shinyFiles. I'll post an issue and see if the shiny/Rstudio folks can provide some suggestions.

Rmarkdown:

    ---
    runtime: shiny
    ---
    
    ```{r setup, include=FALSE}
    library(shinyFiles)
    options(shiny.trace=TRUE)
    ```
    
    ```{r}
    shinySaveButton("saveFileRmd", "Save file", "Save file as ...")    
    shinyFileSave(input, "saveFileRmd", roots = c(home = '~'), session = session)
    ```
     
Shiny App:

    library(shiny)
    library(shinyFiles)
    
    ui <- fluidPage(
      shinySaveButton("saveFileRmd", "Save file", "Save file as ...")
    )
    
    server <- function(input, output, session) {
      shinyFileSave(input, "saveFileRmd", roots = c(home = '~'), session = session)
    }
    
    shinyApp(ui = ui, server = server)

**Comment by aravind211** [comment]
Okay, I tested the following and it worked for me. Please let me know if this works for you:

Rmarkdown:

---
runtime: shiny
---

```{r setup, include=FALSE}
library(shinyFiles)
options(shiny.trace=TRUE)
```

```{r}
renderUI({shinySaveButton("saveFileRmd", "Save file", "Save file as ...") })  
shinyFileSave(input, "saveFileRmd", roots = c(home = '~'), session = session)
```

**Comment by vnijs** [comment]
Nice work @aravind211! The below works, i.e., combining shinyFiles with Rmarkdown (runtime: shiny) and flexdashboards

    ---
    title: "shinyFiles + flexdashboard"
    runtime: shiny
    output: flexdashboard::flex_dashboard
    ---
    
    ```{r setup, include=FALSE}
    library(shinyFiles)
    ```
    
    ```{r echo = FALSE}
    renderUI({shinyFilesButton("file_choose", "Select file", "", multiple = FALSE)})
    shinyFileChoose(input, "file_choose", roots = c(home = '~'))
    ```

**Comment by vnijs** [comment]
Based on @aravind211 insights, it seems this is not an issue in shinyFiles, but rather how Rmarkdown handles shiny inputs. I'll close this for now but feel free to reopen if needed.
