### ISSUE TITLE
Add shinySaveFile component

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/shinyFiles#7]
Very parallel to shinyFileChoose, except for a text-field for writing the name of a new file

**Comment by sjmgarnier** [comment]
Yes, please :-) 

I'm trying to write a rmarkdown editor with instant preview for Shiny (on github soon) and this feature would be very, very useful. I currently use shinyFileChoose for opening existing files and I love it. An equivalent function for saving files would be fantastic.

**Comment by thomasp85** [comment]
@sjmgarnier I have taken this up now and plan on releasing a major update within the next couple of days/weeks. It will also include folder selection, though this seems less important for your use case...

**Comment by sjmgarnier** [comment]
@thomasp85 Fantastic! I'm working on updating the editor to bootstrap3 and I'll make sure to include your new function when it is released. 

BTW, the editor can be found at https://github.com/swarm-lab/editR if you want to give it a try. 

Cheers!

**Comment by thomasp85** [comment]
Added in 4dab867b

**Comment by thomasp85** [comment]
@sjmgarnier Everything in the github repo should be up and running now. There is still some documentation to be done before I submit to CRAN, but you can begin to play around with the functionality now - any feedback is appreciated. See `shinyFilesExample()` for an introduction to the new modules...

**Comment by sjmgarnier** [comment]
@thomasp85 FYI, the latest version of my [`editR`](https://github.com/swarm-lab/editR) package now makes use of the latest functions in `shinyFiles`. Thanks very much for your hard work, it made my life easier and my software better.
