### ISSUE TITLE
feature request: Close modal with escape key

### ISSUE THREAD

**Issue by vnijs** [thomasp85/shinyFiles#76]
Same as `easyClose` with shiny modals. This should be straight forward but it is not clear where to add this in `shinyFiles.js` (thttps://getbootstrap.com/docs/4.0/components/modal/). I hoped that the following would add what I'm looking for but that didn't have any effect.

`$('.sF-modal').modal({keyboard: true});`

**Comment by thomasp85** [comment]
shinyFiles modals are only bootstrap in looks. I’ve chosen not to rely on bootstrap js for behaviour in order to make it possible to forego bootstrap alltogether if you wish to.

I think we should push back new keyboard behaviour to after next release, but it should be pretty simple to implement

**Comment by thomasp85** [comment]
Btw, could you maybe create an issue collecting all ideas for extended keyboard behaviour?
