### ISSUE TITLE
ShinyFilesButton not loading path

### ISSUE THREAD

**Issue by pereznic** [thomasp85/shinyFiles#85]
Dear all,

I've been recently working with the ShinyFiles Library and it seems I cant the ShinyFilesButton work properly. The issue is that pointing at the "volumes" path works when I use the ShinyDirChoose but not when I use it with the ShinyFileChoose. I have not been able to understand if this is indeed a small bug or if It is me mis-using it. I paste the code of a basic app in which replacing ShinyFilesChoose and ShinyFilesButton by ShinyDirChoose and ShinyDirButton works to point to the right directory.

```r

library(shiny)
library(shinyFiles)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Example"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
         shinyFilesButton('button1',label='Files',title='Choose Files',
                          multiple=TRUE),
         shinyDirButton('button2',label='Directories',title='Choose Path')
        
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         textOutput("filenames")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
   
  shinyFileChoose(input,'button11',roots=getVolumes())
  shinyDirChoose(input,"button2",roots=getVolumes())
   
}

# Run the application 
shinyApp(ui = ui, server = server)

```

I'm using R version 3.4.3

**Comment by pereznic** [comment]
@vnijs Thanks for your reply. I just made the change on the previous code (sorry about that). I've been using the <input type=button value="getVolumes()"> function from the <input type=button value="shinyFiles"> package (I paste the code again in case is useful). I can see in the example how this is working, but unfortunately I have not been able to do either of the following things:

1) Set the roots path to a reactive expression that points to a folder that the user chose/created before as the project main folder.

2) Set the roots path to the first main drive by using the "roots=getVolumes()" command in the function parameters (this works for the folder button though).

Regards,

**Comment by vnijs** [comment]
In `shinyFileChoose(input,'button11', roots=getVolumes())` you need `button1`, not `button11`. After this change your example works fine.

For the 2nd question, please provide a minimal example so we can see more clearly what you are trying to do.

**Comment by pereznic** [comment]
Dear Vince, 

Thanks for your help. That was indeed a typo. However, this is not solving my problem. I made a small app as an example as you suggested so you can see what I intend and what my actual problem is. The specific problem I encounter is the rendering of a white file chooser interface when I point to the "volumes" folder as roots in the file chooser (this however works on the directory chooser). Moreover, I asked someone to run the same on a Mac and there it seems to be working properly.  I attach a screenshot of the interface I get (I'm running R 3.4.3 on Windows).

On the other hand, as presented in the example app, I would like to link the file chooser to a folder that was selected before with a directory chooser (meaning the root of button "File Chooser 2" being the folder selected "Choose Folder".

```r

library(shiny)
library(shinyFiles)

# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Example - Shiny Files Buttons Use"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
        p("First press this ShinyDir Button to locate an existing folder and set
          it to be your new working directory"),
        shinyDirButton("folderChoose","Choose Folder","Choose working directory"),
        
        p("In this second step, press the ShinyFiles Button that should point to the 
          volumes (Just as the previous button does). In my R version, this is where it 
          renders a white interface (see attached picture"),
        shinyFilesButton("filesChoose1","Files Chooser 1","Choose your files",
                         multiple=TRUE),
        
        p("In this third button, pI owuld like to link the ShinyFiles interface with
          the selected folder in button 1. This part I have not been able to solve"),
        shinyFilesButton("filesChoose2","Files Chooser 2","Choose your files",
                         multiple=TRUE)
        
      ),
      
      # Show a plot of the generated distribution
      mainPanel(
         verbatimTextOutput("path")
      )
   )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {
   
  volumes = getVolumes()
  shinyDirChoose(input, "folderChoose", roots = volumes, session = session)
  sel_path <- reactive({return(print(parseDirPath(volumes, input$folderChoose)))})
  shinyFileChoose(input, "filesChoose1", roots = volumes, session = session)
  
  
  setWorkingDir<-eventReactive(input$folderChoose,{
    setwd(sel_path())
    })
  
  output$path<-renderText(sel_path())
}

# Run the application 
shinyApp(ui = ui, server = server)

```
[Blank Interface](https://www.dropbox.com/s/mp3j9zxyzi4o5np/Error_ShinyFiles_Chooser_1.png?dl=0)

Regards,

**Comment by vnijs** [comment]
I don't have any issues running the app you posted on Windows or Mac. 

![image](https://user-images.githubusercontent.com/2998956/42547468-2f5bb070-8477-11e8-8723-faf507afbaea.png)

Just in case ... for the very latest version of `shinyFiles` use the command below:

```r
install.packages("shinyFiles", repos = "https://radiant-rstats.github.io/minicran/")
```

You should basically never use `setwd()` in a shiny app. For your `fileChoose2` you need to supply a function to `shinyFileChoose` like in the example below. Tested on Mac and Windows.

```r
library(shiny)
library(shinyFiles)

# Define UI for application that draws a histogram
ui <- fluidPage(

  # Application title
  titlePanel("Example - Shiny Files Buttons Use"),

  # Sidebar with a slider input for number of bins
  sidebarLayout(
    sidebarPanel(
      p("First press this ShinyDir Button to locate an existing folder and set
          it to be your new working directory"),
      shinyDirButton("folderChoose","Choose Folder","Choose working directory"),

      p("In this second step, press the ShinyFiles Button that should point to the
          volumes (Just as the previous button does). In my R version, this is where it
          renders a white interface (see attached picture"),
      shinyFilesButton("filesChoose1","Files Chooser 1","Choose your files",
                       multiple=TRUE),

      p("In this third button, pI owuld like to link the ShinyFiles interface with
          the selected folder in button 1. This part I have not been able to solve"),
      shinyFilesButton("filesChoose2","Files Chooser 2","Choose your files",
                       multiple=TRUE)

    ),

    # Show a plot of the generated distribution
    mainPanel(
      verbatimTextOutput("path")
    )
  )
)

# Define server logic required to draw a histogram
server <- function(input, output, session) {

  volumes <- getVolumes()
  shinyDirChoose(input, "folderChoose", roots = volumes, session = session)
  shinyFileChoose(input, "filesChoose1", roots = volumes, session = session)
  ui_volumes <- function() {
    sel_path <- parseDirPath(volumes, input$folderChoose)
    volumes <- volumes()
    if (length(sel_path) > 0 && !sel_path %in% volumes) {
      vnames <- c(basename(sel_path), names(volumes))
      setNames(c(sel_path, volumes), vnames)
    } else {
      volumes
    }
  }

  shinyFileChoose(input, "filesChoose2", roots = ui_volumes, session = session)
}

# Run the application
shinyApp(ui = ui, server = server)
```

![image](https://user-images.githubusercontent.com/2998956/42548328-6afac1e4-847b-11e8-8810-2308f9a0a4aa.png)

**Comment by pereznic** [comment]
@vnijs Thanks for that! I updated both my R version and the shinyFiles package and now it is working. On the other hand thanks for the function advice, this indeed makes it easier and clearer. Lastly I have one practical question and it regards your advice of never using "setwd" in a shinyapp. I'm working in an app to create some content that would be stored in a destination folder and setting the WD to that folder saves me a lot of path pasting. Would you rather just use path pasting instead of the fixed WD approach?

**Comment by vnijs** [comment]
Thanks for the update @pereznic. In general you should avoid using `setwd` and use `file.path` instead. Good luck with the app!

**Comment by woodwards** [comment]
Sorry to bump this, but I get the following when I run your example on Windows 10:

```
> runApp('shiny_files_test2.R')

Listening on http://127.0.0.1:7893
Warning: Error in system: 'wmic' not found
  49: system
  48: roots
  47: <Anonymous>
  45: sendDirectoryData
  44: <observer>
   1: runApp
```

**Comment by woodwards** [comment]
For some reason wmic.exe is not in the system, path. I can find it using this, but might not work on all systems.

```
old_path <- Sys.getenv("PATH")
new_path <- "c:/windows/System32/Wbem"
Sys.setenv(PATH = paste(old_path, new_path, sep = ";"))
```

**Comment by vnijs** [comment]
Thanks for reporting @woodwards. `wmic` has been used in shinyFiles for some time and this is the first time I have seen this issue mentioned. To be honest, if this is a new setting in Windows 10 I'm not sure what the alternative is.
