### ISSUE TITLE
shinyFiles does not work with chinese, russian, etc. characters on Windows

### ISSUE THREAD

**Issue by vnijs** [thomasp85/shinyFiles#87]
Currently shinyFiles does not work with chinese, russian, etc. characters on Windows. This can be traced back to base R functions such as `list.files`. I have been working on a PR for shinyFiles that addresses this problem (see last screenshot below). However, it would require a dependency on the [`fs`](https://github.com/r-lib/fs) and possibly `tibble` due to a bug in `print.data.frame` in base R. It would also build on PR https://github.com/thomasp85/shinyFiles/pull/86. Are you open to this idea @thomasp85? 

cc @thercast 

```
> list.files("C:/Users/vnijs/Desktop/sf", full.names = TRUE)
[1] "C:/Users/vnijs/Desktop/sf/???"    "C:/Users/vnijs/Desktop/sf/?????"  "C:/Users/vnijs/Desktop/sf/folder"
> fs::dir_ls("C:/Users/vnijs/Desktop/sf")
C:/Users/vnijs/Desktop/sf/folder C:/Users/vnijs/Desktop/sf/папка  C:/Users/vnijs/Desktop/sf/萼片长 
```

Actual folder content:
![image](https://user-images.githubusercontent.com/2998956/43360370-2102dc10-9269-11e8-9fdb-7161c39dac10.png)

Current shinyFiles:
![image](https://user-images.githubusercontent.com/2998956/43360368-1445981e-9269-11e8-8507-ce84918bc228.png)

Proposed PR with shinyFiles and `fs`:

![image](https://user-images.githubusercontent.com/2998956/43360415-c9918e26-9269-11e8-86ea-f4f3b1290ba2.png)

**Comment by thercast** [comment]
From my perspective I think it is reasonable to import `fs` and possible `tibble`, since they are supposed to be fairly light-weight.  In particular `fs` provides a cleaner interface to many of the base R file-based functions.

**Comment by vnijs** [comment]
@thomasp85 Any change you could comment on this issue review the PR in the next few days? Thanks

**Comment by vnijs** [comment]
@thomasp85 ... bump ... I know you are probably swamped with gganimate so if you are open to providing push permission that would work for me as well

**Comment by thomasp85** [comment]
I think using both fs and nibble are fine - shinyFiles is deeply coupled with RStudio anyway

**Comment by vnijs** [comment]
@thomasp85 and @thercast Please tryout the latest version if you have a moment. If all looks as good as on my test machines it would be great to push this version to CRAN

devtools::install_github("thomasp85/shinyFiles")

**Comment by thomasp85** [comment]
Doesn’t it require the development version of fs? In that case we are contingent and an fs update before we can release to CRAN

**Comment by vnijs** [comment]
Fs 1,2,6 is on CRAN now and that is the version we need. Would be great to have some of the JS features mentioned in the issues working but I would need help on those.

**Comment by vnijs** [comment]
PR https://github.com/thomasp85/shinyFiles/pull/92 merged
