### ISSUE TITLE
set default values

### ISSUE THREAD

**Issue by ycphs** [thomasp85/shinyFiles#89]
Dear all,

Currently it is not possiible to set default values for directories or selected files.

It would be helpful, if the optional parameter can be set.

**Comment by vnijs** [comment]
You can set `defaultPath` and `defaultRoot` for both `shinyDirChoose` and `shinyFileChoose`. Can you be more explicit about what you are trying to do?

**Comment by ycphs** [comment]
The pre-selection of a file (e.g. config-file) is not possible.

"standard_config.json" is the standard file I want to choose, but in case i want to change it to the file "alt1_config.json"

with `defaultRoot` and `defaultPath` it doesn't work.

**Comment by vnijs** [comment]
I'll close this issue for now. If you have additional questions/comments please open another issue

**Comment by floriandeboissieu** [comment]
I have a similar question for shinyFileSave, would it be possible to have a default in input text div called "filename"?

**Comment by vnijs** [comment]
As you can see from `?shinyFiles::shinySaveButton` there is already a `filename` argument where you can set a default. I that not what you are asking about?

**Comment by floriandeboissieu** [comment]
Yes it is, sorry for the question.
