### ISSUE TITLE
changes in shinyFileChoose from 0.6.2 to 0.7.0 

### ISSUE THREAD

**Issue by SteffenKothe** [thomasp85/shinyFiles#90]
Dear developers, 

recently I updated the shinyFiles package from 0.6.2 to 0.7.0 and
got some trouble, which I could not fix so far.
Could you please describe what the changes in shinyFileChoose are?

The following code is part of an important script, and it worked fine
with version 0.6.2.

Do you have any hint for me to solve this issue?

```
shinyFileChoose(input,'file2',session=session,roots=root)
  
  instat.data <- reactive({
    if(!is.null(input$file2) && as.character(input$file2) != "0"){
      fs <- parseFilePaths(root, input$file2)
      if(grepl("RData",as.character(fs$datapath))){
        a <- get(load(as.character(fs$datapath)))
        a <- as.data.frame(a)
        a
      }
    }
  })
  
  observeEvent(input$file2, {
    if(!is.null(input$file2) && as.character(input$file2) != "0"){
      fs <- parseFilePaths(root, input$file2)
      if(grepl("RData",as.character(fs$datapath))){
        plot_rinstat(plot_rinstat()+1)
        plot_rinstat2(plot_rinstat2()+1)
      }
    }
  })

```  

It should only go into the first if loop if a file is selected, but now it is going
into this loop even if nothing is selected. When I plot the value of input$file2
without selecting a file it gives 0. Thus, input$file2 seems to be unknown for 
the if statement inside reactive.
Did anything change concerning the usage within the reactive command?

Thanks for your help.

**Comment by vnijs** [comment]
Try `if (!is.integer(input$uploadfile)) { ...`

**Comment by SteffenKothe** [comment]
Ok, much easier than I thought. Thanks a lot. I still don't know why it was working with 0.6.2 and not with 0.7.0.

**Comment by vnijs** [comment]
That was a breaking change introduced to deal with various other issues. It would be useful to add some more examples to illustrate how this changes usage of `parseFilePath`

**Comment by wolfpack12** [comment]
Correct me if I’m wrong, but I think execution of the shinyFileChoose in 0.6.2 occurs PRIOR to the observeEvent on the object. In 0.7.0, it occurs AFTER. That means you have to handle an event trigger where no file has been selected.

We solved this by doing an if(length(input$filechoose)==1) return(). Haven’t tried the approach above.

**Comment by wolfpack12** [comment]
What’s the appropriate strategy for handling pre-click execution? I believe the strategy of using !is.integer will work if the button has not been previously clicked. What if users click it multiple times and we only want to parse the file path afterwards?

**Comment by vnijs** [comment]
If the value can be NULL add `req(input$my_sf_button)`.

Add an `observe({ print(input$my_sf_button })` in your code and you will see what values `my_sf_button` can take. As mentioned, shinyFile* buttons are now basically like actionButtons and clicking increases the (integer) value.

**Comment by vnijs** [comment]
Closing. Please open a new issue if needed
