### ISSUE TITLE
having some trouble with shinySaveButton  after update to 0.7.0

### ISSUE THREAD

**Issue by stranda** [thomasp85/shinyFiles#93]
Hi,
I've been using shinyFiles for a while in a package I maintain (CRAN/skeleSim) and it's been great.  Unfortunately with the new version (0.7.0) I'm getting errors in code that uses shinySaveButton().  This is the case on both my linux systems and some users macOS systems.  Basically it looks like parseSavePath is returning a null whereas it returned a good path in 0.6.2.

here is the relevant line from my ui:
########################################################################
        shinySaveButton("ssClassSave","Save skelesim object to file","Save parameter file",
                        filetype=list(ssClass=c("rdata","Rdata","rda")))

and here is my relevant server code:
########################################################################
shinyFileSave(input, 'ssClassSave', filetypes=c("rdata","RData","RDATA","rData","rda"), session=session, roots=VolumeRoots)
###

observeEvent(input$ssClassSave,
{

    path <- as.character(parseSavePath(VolumeRoots,input$ssClassSave)$datapath)
    fn <- basename(path)
    dir <- normalizePath(dirname(path))
    
    assign("ssClass",rValues$ssClass)
    save(file=paste0(dir,"/",fn),list="ssClass")
})

no doubt this is my misuse of the new system, but I'm having a little problem grokking how I need to make changes to keep up.

thanks for any help.
allan

**Comment by vnijs** [comment]
@stranda Please take a look at the discussion in the issue linked below. Let us know is that addresses the issue you are seeing.

https://github.com/thomasp85/shinyFiles/issues/90

**Comment by vnijs** [comment]
@stranda Were you able to resolve the issue?

**Comment by vnijs** [comment]
I'll assume the issue is resolved now. If not, feel free to reopen
