### ISSUE TITLE
Issue with "modified" and "created" headers in shinyFileChoose dialog

### ISSUE THREAD

**Issue by cactus74** [thomasp85/shinyFiles#96]
First of all, thanks for the great package !

On UNIX filesystem, ctime happens to mean "last change time", not "creation time". The header "created" in the file selection dialog is ill chosen from my perspective. I personally think it should simply be fully discarded. 

In shinyFiles.js:

`      case 'Created':
        fileList.sortChildren(function(elem) {
          return $(elem).data('sF-file') ? $(elem).data('sF-file').cTime : new Date();
        }, direction == 'descending');
        break;
`

**Comment by vnijs** [comment]
Thanks for the report @cactus74. We now use the `fs` package to determine the `birth_time` or `creation time` of a file or directory. Please try the version on GitHub to see the change
